/* Generated by gliss-attr (119/02/20 18:19:48) copyright (c) 2009 IRIT - UPS */

#include <arm/api.h>
#include <arm/id.h>
#include <arm/macros.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef t::uint16 (*multi_fun_t)(arm_inst_t *inst);

static t::uint16 otawa_multi_UNKNOWN(arm_inst_t *inst) {
        return 0;
}

static t::uint16 otawa_multi_MOV_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MOVS_RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_TST_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SUBS_RD__RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SUB_SP___ID__2A_4(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SUBS_RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SUBS_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRH_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRH_RD___LT_RD___ID__2A_2_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRB_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRB_RD___LT_RD___ID_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STR_RD___LT_SP___ID__2A_4_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STR_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STR_RD___LT_RD___ID__2A_4_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STMIA_RD_21___LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SBCS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RORS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_PUSH__LB_SS_RB_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_PUSH__LB_SS_RB__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_POP__LB_SS_RB_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_POP__LB_SS_RB__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ORRS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_NEGS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MVNS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MULS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LSRS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LSRS_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LSLS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LSLS_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSH_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSB_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRH_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRH_RD___LT_RD___ID__2A_2_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRB_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRB_RD___LT_RD___ID_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDR_RD___LT_SP___ID__2A_4_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDR_RD___LT_PC___ID__2A_4_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDR_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDR_RD___LT_RD___ID__2A_4_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDMIA_RD_21___LB_S_RB_(arm_inst_t *inst) {
	return ARM_LDMIA_RD_21___LB_S_RB__i_x_llist_r;

};

static t::uint16 otawa_multi_EORS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMP_RD__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMP_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMP_RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMN_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BX_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BLX_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BL_LR___I08X(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BICS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_S_08X(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ASRS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ASRS_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ANDS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADD_RD__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDS_RD__RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADD_SP__SP___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADD_RD__SP___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADD_RD__PC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDS_RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDS_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADCS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MRCS_D__D__S__CRD__CRD__D(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDCSS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDCSS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDCSS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDCSS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STCSS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STCSS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STCSS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STCSS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MRSS_S__CPSR(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MRSS_S__SPSR(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR___S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FSXC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_SXC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FXC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FSX__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_XC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_SC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_SX__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_F__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FX__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FS__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_C__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_X__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_F__S_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR___S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FSXC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_SXC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FXC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FSX__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_XC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_SC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_SX__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_F__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FX__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FS__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_C__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_X__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_F__S_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR____ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FSXC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_SXC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FXC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FSX___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_XC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_SC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_SX___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_F___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FX___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FS___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_C___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_X___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_F___ID_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR____ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FSXC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_SXC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FXC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FSX___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_XC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_SC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_SX___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_F___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FX___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FS___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_C___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_X___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_F___ID_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CDPS_D__D__D__D__D__D(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BFIS_S___ID___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CLZS_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SWPS_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SWPSB_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UMLALSS_S_S_S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SMLALSS_S_S_S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UMULLSS_S_S_S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SMULLSS_S_S_S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MULSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MLASS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SWIS_D(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDMSS_SS___LB_S_RB_S(arm_inst_t *inst) {
	return ARM_LDMSS_SS___LB_S_RB_S_x_reglist_r;

};

static t::uint16 otawa_multi_STMSS_SS___LB_S_RB_S(arm_inst_t *inst) {
	return ARM_STMSS_SS___LB_S_RB_S_x_reglist_r;

};

static t::uint16 otawa_multi_LDRSSH_S___LT_SS_SSSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSSH_S___LT_SS_S_ILUSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSSB_S___LT_SS_SSSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSSB_S___LT_SS_S_ILUSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSH_S___LT_SS_SSSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSH_S___LT_SS_S_ILUSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRSH_S___LT_SS_SSSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRSH_S___LT_SS_S_ILUSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRSSS_S___LT_SS__SS__S__IDSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSSS_S___LT_SS__SS__S__IDSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRSSS_S___LT_SS___ISDSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSSS_S___LT_SS___ISDSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BSS_X(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BXS_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_TSTS_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_TSTS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_TSTS_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_TEQS_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_TEQS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_TEQS_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SUBSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SUBSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SUBSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SBCSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SBCSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SBCSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RSCSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RSCSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RSCSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RSBSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RSBSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RSBSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ORRSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ORRSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ORRSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MVNSS_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MVNSS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MVNSS_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MOVSS_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MOVSS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MOVSS_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_EORSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_EORSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_EORSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMPS_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMPS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMPS_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMNS_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMNS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMNS_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BICSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BICSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BICSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ANDSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ANDSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ANDSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADCSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADCSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADCSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDSS_S__S___ID(arm_inst_t *inst) {
return 0;
};




/* function table */
static multi_fun_t arm_multi_table[] = {
	otawa_multi_UNKNOWN,
	otawa_multi_MOV_S__S,
	otawa_multi_MOVS_RD___ID,
	otawa_multi_TST_RD__RD,
	otawa_multi_SUBS_RD__RD__RD,
	otawa_multi_SUB_SP___ID__2A_4,
	otawa_multi_SUBS_RD___ID,
	otawa_multi_SUBS_RD__RD___ID,
	otawa_multi_STRH_RD___LT_RD__RD__RT_,
	otawa_multi_STRH_RD___LT_RD___ID__2A_2_RT_,
	otawa_multi_STRB_RD___LT_RD__RD__RT_,
	otawa_multi_STRB_RD___LT_RD___ID_RT_,
	otawa_multi_STR_RD___LT_SP___ID__2A_4_RT_,
	otawa_multi_STR_RD___LT_RD__RD__RT_,
	otawa_multi_STR_RD___LT_RD___ID__2A_4_RT_,
	otawa_multi_STMIA_RD_21___LB_S_RB_,
	otawa_multi_SBCS_RD__RD,
	otawa_multi_RORS_RD__RD,
	otawa_multi_PUSH__LB_SS_RB_,
	otawa_multi_PUSH__LB_SS_RB__0,
	otawa_multi_POP__LB_SS_RB_,
	otawa_multi_POP__LB_SS_RB__0,
	otawa_multi_ORRS_RD__RD,
	otawa_multi_NEGS_RD__RD,
	otawa_multi_MVNS_RD__RD,
	otawa_multi_MULS_RD__RD,
	otawa_multi_LSRS_RD__RD,
	otawa_multi_LSRS_RD__RD___ID,
	otawa_multi_LSLS_RD__RD,
	otawa_multi_LSLS_RD__RD___ID,
	otawa_multi_LDRSH_RD___LT_RD__RD__RT_,
	otawa_multi_LDRSB_RD___LT_RD__RD__RT_,
	otawa_multi_LDRH_RD___LT_RD__RD__RT_,
	otawa_multi_LDRH_RD___LT_RD___ID__2A_2_RT_,
	otawa_multi_LDRB_RD___LT_RD__RD__RT_,
	otawa_multi_LDRB_RD___LT_RD___ID_RT_,
	otawa_multi_LDR_RD___LT_SP___ID__2A_4_RT_,
	otawa_multi_LDR_RD___LT_PC___ID__2A_4_RT_,
	otawa_multi_LDR_RD___LT_RD__RD__RT_,
	otawa_multi_LDR_RD___LT_RD___ID__2A_4_RT_,
	otawa_multi_LDMIA_RD_21___LB_S_RB_,
	otawa_multi_EORS_RD__RD,
	otawa_multi_CMP_RD__S,
	otawa_multi_CMP_RD__RD,
	otawa_multi_CMP_RD___ID,
	otawa_multi_CMN_RD__RD,
	otawa_multi_BX_S,
	otawa_multi_BLX_S,
	otawa_multi_BL_LR___I08X,
	otawa_multi_BICS_RD__RD,
	otawa_multi_S_08X,
	otawa_multi_ASRS_RD__RD,
	otawa_multi_ASRS_RD__RD___ID,
	otawa_multi_ANDS_RD__RD,
	otawa_multi_ADD_RD__S,
	otawa_multi_ADDS_RD__RD__RD,
	otawa_multi_ADD_SP__SP___ID,
	otawa_multi_ADD_RD__SP___ID,
	otawa_multi_ADD_RD__PC___ID,
	otawa_multi_ADDS_RD___ID,
	otawa_multi_ADDS_RD__RD___ID,
	otawa_multi_ADCS_RD__RD,
	otawa_multi_MRCS_D__D__S__CRD__CRD__D,
	otawa_multi_LDCSS_D__D___LT_RD_RT___D,
	otawa_multi_LDCSS_D__D___LT_RD_RT____ISD,
	otawa_multi_LDCSS_D__D___LT_RD___ISD_RT__21,
	otawa_multi_LDCSS_D__D___LT_RD___ISD_RT_,
	otawa_multi_STCSS_D__D___LT_RD_RT___D,
	otawa_multi_STCSS_D__D___LT_RD_RT____ISD,
	otawa_multi_STCSS_D__D___LT_RD___ISD_RT__21,
	otawa_multi_STCSS_D__D___LT_RD___ISD_RT_,
	otawa_multi_MRSS_S__CPSR,
	otawa_multi_MRSS_S__SPSR,
	otawa_multi_MSRS_CPSR___S,
	otawa_multi_MSRS_CPSR_FSXC__S,
	otawa_multi_MSRS_CPSR_SXC__S,
	otawa_multi_MSRS_CPSR_FXC__S,
	otawa_multi_MSRS_CPSR_FSX__S,
	otawa_multi_MSRS_CPSR_XC__S,
	otawa_multi_MSRS_CPSR_SC__S,
	otawa_multi_MSRS_CPSR_SX__S,
	otawa_multi_MSRS_CPSR_F__S,
	otawa_multi_MSRS_CPSR_FX__S,
	otawa_multi_MSRS_CPSR_FS__S,
	otawa_multi_MSRS_CPSR_C__S,
	otawa_multi_MSRS_CPSR_X__S,
	otawa_multi_MSRS_CPSR_S__S,
	otawa_multi_MSRS_CPSR_F__S_0,
	otawa_multi_MSRS_SPSR___S,
	otawa_multi_MSRS_SPSR_FSXC__S,
	otawa_multi_MSRS_SPSR_SXC__S,
	otawa_multi_MSRS_SPSR_FXC__S,
	otawa_multi_MSRS_SPSR_FSX__S,
	otawa_multi_MSRS_SPSR_XC__S,
	otawa_multi_MSRS_SPSR_SC__S,
	otawa_multi_MSRS_SPSR_SX__S,
	otawa_multi_MSRS_SPSR_F__S,
	otawa_multi_MSRS_SPSR_FX__S,
	otawa_multi_MSRS_SPSR_FS__S,
	otawa_multi_MSRS_SPSR_C__S,
	otawa_multi_MSRS_SPSR_X__S,
	otawa_multi_MSRS_SPSR_S__S,
	otawa_multi_MSRS_SPSR_F__S_0,
	otawa_multi_MSRS_CPSR____ID,
	otawa_multi_MSRS_CPSR_FSXC___ID,
	otawa_multi_MSRS_CPSR_SXC___ID,
	otawa_multi_MSRS_CPSR_FXC___ID,
	otawa_multi_MSRS_CPSR_FSX___ID,
	otawa_multi_MSRS_CPSR_XC___ID,
	otawa_multi_MSRS_CPSR_SC___ID,
	otawa_multi_MSRS_CPSR_SX___ID,
	otawa_multi_MSRS_CPSR_F___ID,
	otawa_multi_MSRS_CPSR_FX___ID,
	otawa_multi_MSRS_CPSR_FS___ID,
	otawa_multi_MSRS_CPSR_C___ID,
	otawa_multi_MSRS_CPSR_X___ID,
	otawa_multi_MSRS_CPSR_S___ID,
	otawa_multi_MSRS_CPSR_F___ID_0,
	otawa_multi_MSRS_SPSR____ID,
	otawa_multi_MSRS_SPSR_FSXC___ID,
	otawa_multi_MSRS_SPSR_SXC___ID,
	otawa_multi_MSRS_SPSR_FXC___ID,
	otawa_multi_MSRS_SPSR_FSX___ID,
	otawa_multi_MSRS_SPSR_XC___ID,
	otawa_multi_MSRS_SPSR_SC___ID,
	otawa_multi_MSRS_SPSR_SX___ID,
	otawa_multi_MSRS_SPSR_F___ID,
	otawa_multi_MSRS_SPSR_FX___ID,
	otawa_multi_MSRS_SPSR_FS___ID,
	otawa_multi_MSRS_SPSR_C___ID,
	otawa_multi_MSRS_SPSR_X___ID,
	otawa_multi_MSRS_SPSR_S___ID,
	otawa_multi_MSRS_SPSR_F___ID_0,
	otawa_multi_CDPS_D__D__D__D__D__D,
	otawa_multi_BFIS_S___ID___ID,
	otawa_multi_CLZS_S__S,
	otawa_multi_SWPS_S__S___LT_S_RT_,
	otawa_multi_SWPSB_S__S___LT_S_RT_,
	otawa_multi_UMLALSS_S_S_S_S,
	otawa_multi_SMLALSS_S_S_S_S,
	otawa_multi_UMULLSS_S_S_S_S,
	otawa_multi_SMULLSS_S_S_S_S,
	otawa_multi_MULSS_S__S__S,
	otawa_multi_MLASS_S__S__S__S,
	otawa_multi_SWIS_D,
	otawa_multi_LDMSS_SS___LB_S_RB_S,
	otawa_multi_STMSS_SS___LB_S_RB_S,
	otawa_multi_LDRSSH_S___LT_SS_SSSS,
	otawa_multi_LDRSSH_S___LT_SS_S_ILUSS,
	otawa_multi_LDRSSB_S___LT_SS_SSSS,
	otawa_multi_LDRSSB_S___LT_SS_S_ILUSS,
	otawa_multi_LDRSH_S___LT_SS_SSSS,
	otawa_multi_LDRSH_S___LT_SS_S_ILUSS,
	otawa_multi_STRSH_S___LT_SS_SSSS,
	otawa_multi_STRSH_S___LT_SS_S_ILUSS,
	otawa_multi_STRSSS_S___LT_SS__SS__S__IDSS,
	otawa_multi_LDRSSS_S___LT_SS__SS__S__IDSS,
	otawa_multi_STRSSS_S___LT_SS___ISDSS,
	otawa_multi_LDRSSS_S___LT_SS___ISDSS,
	otawa_multi_BSS_X,
	otawa_multi_BXS_S,
	otawa_multi_TSTS_S___ID,
	otawa_multi_TSTS_S__S__S_S,
	otawa_multi_TSTS_S__S,
	otawa_multi_TEQS_S___ID,
	otawa_multi_TEQS_S__S__S_S,
	otawa_multi_TEQS_S__S,
	otawa_multi_SUBSS_S__S___ID,
	otawa_multi_SUBSS_S__S__S__S_S,
	otawa_multi_SUBSS_S__S__S,
	otawa_multi_SBCSS_S__S___ID,
	otawa_multi_SBCSS_S__S__S__S_S,
	otawa_multi_SBCSS_S__S__S,
	otawa_multi_RSCSS_S__S___ID,
	otawa_multi_RSCSS_S__S__S__S_S,
	otawa_multi_RSCSS_S__S__S,
	otawa_multi_RSBSS_S__S___ID,
	otawa_multi_RSBSS_S__S__S__S_S,
	otawa_multi_RSBSS_S__S__S,
	otawa_multi_ORRSS_S__S___ID,
	otawa_multi_ORRSS_S__S__S__S_S,
	otawa_multi_ORRSS_S__S__S,
	otawa_multi_MVNSS_S___ID,
	otawa_multi_MVNSS_S__S__S_S,
	otawa_multi_MVNSS_S__S,
	otawa_multi_MOVSS_S___ID,
	otawa_multi_MOVSS_S__S__S_S,
	otawa_multi_MOVSS_S__S,
	otawa_multi_EORSS_S__S___ID,
	otawa_multi_EORSS_S__S__S__S_S,
	otawa_multi_EORSS_S__S__S,
	otawa_multi_CMPS_S___ID,
	otawa_multi_CMPS_S__S__S_S,
	otawa_multi_CMPS_S__S,
	otawa_multi_CMNS_S___ID,
	otawa_multi_CMNS_S__S__S_S,
	otawa_multi_CMNS_S__S,
	otawa_multi_BICSS_S__S___ID,
	otawa_multi_BICSS_S__S__S__S_S,
	otawa_multi_BICSS_S__S__S,
	otawa_multi_ANDSS_S__S___ID,
	otawa_multi_ANDSS_S__S__S__S_S,
	otawa_multi_ANDSS_S__S__S,
	otawa_multi_ADDSS_S__S__S__S_S,
	otawa_multi_ADDSS_S__S__S,
	otawa_multi_ADCSS_S__S___ID,
	otawa_multi_ADCSS_S__S__S__S_S,
	otawa_multi_ADCSS_S__S__S,
	otawa_multi_ADDSS_S__S___ID
};



/**
 * Get the multiple-register count of the instruction.
 * @return multiple-register count.
 */
t::uint16 arm_multi(arm_inst_t *inst) {
	return arm_multi_table[inst->ident](inst);
}

#ifdef __cplusplus
}
#endif

