/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#ifndef ARM_ARM_INCLUDE_ARM_CODE_H
#define ARM_ARM_INCLUDE_ARM_CODE_H


#if defined(__cplusplus)
extern  "C"
{
#endif


#define ARM_CODE_STATE
#define ARM_CODE_INIT(s)
#define ARM_CODE_DESTROY(s)

#if defined(__cplusplus)
}
#endif

#endif /* ARM_ARM_INCLUDE_ARM_CODE_H */
