/* Generated by gep (119/02/19 20:43:56) copyright (c) 2008 IRIT - UPS */

#ifndef GLISS_ARM_INCLUDE_ARM_DECODE_H
#define GLISS_ARM_INCLUDE_ARM_DECODE_H


#if defined(__cplusplus)
extern  "C"
{
#endif

#define ARM_DECODE_STATE
#define ARM_DECODE_INIT(s)
#define ARM_DECODE_DESTROY(s)

#if defined(__cplusplus)
}
#endif

#endif /* GLISS_ARM_INCLUDE_ARM_DECODE_H */
