/* Generated by gep (118/02/19 18:37:51) copyright (c) 2008 IRIT - UPS */

#ifndef GLISS_ARM_INCLUDE_ARM_FETCH_H
#define GLISS_ARM_INCLUDE_ARM_FETCH_H


#if defined(__cplusplus)
extern  "C"
{
#endif

#include "api.h"
#include "config.h"

#define ARM_FETCH_STATE
#define ARM_FETCH_INIT(s)
#define ARM_FETCH_DESTROY(s)

/* fetch structure */
struct arm_fetch_t
{
	/* the memory which we are supposed to fetch from, useful on Harvard architectures where we deal with several memories */
	arm_memory_t *mem;
/* state used to determine correct fetch */
	arm_state_t *state;};

#if defined(__cplusplus)
}
#endif

#endif /* GLISS_ARM_INCLUDE_ARM_FETCH_H */
