/* Generated by gliss-attr (119/02/19 20:46:34) copyright (c) 2009 IRIT - UPS */

#include <arm/api.h>
#include <arm/id.h>
#include <arm/macros.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef uint32_t otawa_target_t;

typedef otawa_target_t (*target_fun_t)(arm_inst_t *inst);



static otawa_target_t otawa_target_UNKNOWN(arm_inst_t *inst)
{
        /* this code should also be used as default value if
        an instruction has no otawa_target field */
        return 0;
}

static otawa_target_t otawa_target_UXTAHS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UXTAB16S_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UXTABS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_USUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_USUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_USAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_USATS_S___ID__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_USADA8S_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UQSUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UQSUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UQSAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UQASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UQADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UQADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UMULLS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UMLALS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UMAALS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UHSUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UHSUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UHSAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UHASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UHADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UHADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UDIVS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UBFXS_S__S___ID___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SXTAHS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SXTAB16S_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SXTABS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBWS_S__S___ID_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SSUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SSUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SSAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SSATS_S___ID__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SMULLS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SMMLSSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SMMLASS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SMLSLDSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SMLSDSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SMLAWSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SMLALDSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SMLALSSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SMLALS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SMLADSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SMLASSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SHSUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SHSUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SHSAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SHASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SHADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SHADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SELS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SDIVS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SBFXS_S__S___ID___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SBCSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SBCSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RSBSS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RORSS_W_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_REVSHS_W_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_REV16S_W_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_REVS_W_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RBITS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_QSUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_QSUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_QSUBS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_QSAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_QDSUBS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_QDADDS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_QASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_QADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_QADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_QADDS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_PKHBTS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORNSS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORNSS_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MRRCSS_D__D__S__S__CRD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MRCSS_D__D__S__CRD__CRD___LB_D_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MLSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MLAS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MCRRSS_D__D__S__S__CRD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MCRSS_D__D__S__CRD__CRD___LB_D_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LSRSS_W_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDMDBS_SS___LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EORSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EORSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CLZS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CDPSS_D__D__CRD__CRD__CRD___LB_D_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BICSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BICSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BFIS_S__S___ID___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BS_W_08X(arm_inst_t *inst) {
	return (((int32_t)((ARM_BS_W_08X___IADDR + 4))) + __ARM_EXTS32(7, ((int32_t)(arm_concat32(arm_concat32(arm_concat16(arm_concat8(arm_concat8(ARM_BS_W_08X_i_x_S_set, __ARM_MASK32(1, ~(ARM_BS_W_08X_i_x_j1 ^ ARM_BS_W_08X_i_x_S_set)), 1, 1), __ARM_MASK32(1, ~(ARM_BS_W_08X_i_x_j2 ^ ARM_BS_W_08X_i_x_S_set)), 2, 1), ARM_BS_W_08X_i_x_imm10, 3, 10), ARM_BS_W_08X_i_x_imm11, 13, 11), arm_bit32(0, 0), 24, 1)))));

};

static otawa_target_t otawa_target_BS_W_08X_0(arm_inst_t *inst) {
	return (((int32_t)((ARM_BS_W_08X_0___IADDR + 4))) + __ARM_EXTS32(11, ((int32_t)(arm_concat32(arm_concat32(arm_concat16(arm_concat8(arm_concat8(ARM_BS_W_08X_0_i_x_S_set, ARM_BS_W_08X_0_i_x_j2, 1, 1), ARM_BS_W_08X_0_i_x_j1, 2, 1), ARM_BS_W_08X_0_i_x_imm6, 3, 6), ARM_BS_W_08X_0_i_x_imm11, 9, 11), arm_bit32(0, 0), 20, 1)))));

};

static otawa_target_t otawa_target_MOVTS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORRS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MOVWS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORRSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ASRSS_W_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ANDSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ANDSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDWS_S__S___ID_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADCSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADCSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_PLIS__LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_PLIS__LT_PC_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_PLIS__LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_PLIS__LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_PLDSS__LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_PLDSS__LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_PLDSS__LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RSBSS_W_S__S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(ARM_RSBSS_W_S__S___ID_i_x_Rn_r)) == 15)) {
		if((arm_field16(arm_concat16(arm_concat8(ARM_RSBSS_W_S__S___ID_i_x_i, ARM_RSBSS_W_S__S___ID_i_x_imm3, 1, 3), ARM_RSBSS_W_S__S___ID_i_x_imm8, 4, 8), 11, 10) == 0)) {
			switch(arm_field16(arm_concat16(arm_concat8(ARM_RSBSS_W_S__S___ID_i_x_i, ARM_RSBSS_W_S__S___ID_i_x_imm3, 1, 3), ARM_RSBSS_W_S__S___ID_i_x_imm8, 4, 8), 9, 8)) {
			case 0:
				__gtmp_0 = ((uint32_t)(arm_field16(arm_concat16(arm_concat8(ARM_RSBSS_W_S__S___ID_i_x_i, ARM_RSBSS_W_S__S___ID_i_x_imm3, 1, 3), ARM_RSBSS_W_S__S___ID_i_x_imm8, 4, 8), 7, 0)));
				break;
			case 1:
				__gtmp_0 = arm_concat32(arm_concat32(arm_concat16(0, arm_field16(arm_concat16(arm_concat8(ARM_RSBSS_W_S__S___ID_i_x_i, ARM_RSBSS_W_S__S___ID_i_x_imm3, 1, 3), ARM_RSBSS_W_S__S___ID_i_x_imm8, 4, 8), 7, 0), 8, 8), 0, 16, 8), arm_field16(arm_concat16(arm_concat8(ARM_RSBSS_W_S__S___ID_i_x_i, ARM_RSBSS_W_S__S___ID_i_x_imm3, 1, 3), ARM_RSBSS_W_S__S___ID_i_x_imm8, 4, 8), 7, 0), 24, 8);
				break;
			case 2:
				__gtmp_0 = arm_concat32(arm_concat32(arm_concat16(arm_field16(arm_concat16(arm_concat8(ARM_RSBSS_W_S__S___ID_i_x_i, ARM_RSBSS_W_S__S___ID_i_x_imm3, 1, 3), ARM_RSBSS_W_S__S___ID_i_x_imm8, 4, 8), 7, 0), 0, 8, 8), arm_field16(arm_concat16(arm_concat8(ARM_RSBSS_W_S__S___ID_i_x_i, ARM_RSBSS_W_S__S___ID_i_x_imm3, 1, 3), ARM_RSBSS_W_S__S___ID_i_x_imm8, 4, 8), 7, 0), 16, 8), 0, 24, 8);
				break;
			case 3:
				__gtmp_0 = arm_concat32(arm_concat32(arm_concat16(arm_field16(arm_concat16(arm_concat8(ARM_RSBSS_W_S__S___ID_i_x_i, ARM_RSBSS_W_S__S___ID_i_x_imm3, 1, 3), ARM_RSBSS_W_S__S___ID_i_x_imm8, 4, 8), 7, 0), arm_field16(arm_concat16(arm_concat8(ARM_RSBSS_W_S__S___ID_i_x_i, ARM_RSBSS_W_S__S___ID_i_x_imm3, 1, 3), ARM_RSBSS_W_S__S___ID_i_x_imm8, 4, 8), 7, 0), 8, 8), arm_field16(arm_concat16(arm_concat8(ARM_RSBSS_W_S__S___ID_i_x_i, ARM_RSBSS_W_S__S___ID_i_x_imm3, 1, 3), ARM_RSBSS_W_S__S___ID_i_x_imm8, 4, 8), 7, 0), 16, 8), arm_field16(arm_concat16(arm_concat8(ARM_RSBSS_W_S__S___ID_i_x_i, ARM_RSBSS_W_S__S___ID_i_x_imm3, 1, 3), ARM_RSBSS_W_S__S___ID_i_x_imm8, 4, 8), 7, 0), 24, 8);
				break;
			}
			__gtmp_1 = __gtmp_0;
		}
		else
			__gtmp_1 = arm_rotate_right32(32, ((uint32_t)(arm_concat8(1, arm_field16(arm_concat16(arm_concat8(ARM_RSBSS_W_S__S___ID_i_x_i, ARM_RSBSS_W_S__S___ID_i_x_imm3, 1, 3), ARM_RSBSS_W_S__S___ID_i_x_imm8, 4, 8), 6, 0), 1, 7))), arm_field16(arm_concat16(arm_concat8(ARM_RSBSS_W_S__S___ID_i_x_i, ARM_RSBSS_W_S__S___ID_i_x_imm3, 1, 3), ARM_RSBSS_W_S__S___ID_i_x_imm8, 4, 8), 11, 7));
		__gtmp_2 = ((ARM_RSBSS_W_S__S___ID___IADDR + 4) - __gtmp_1);
	}
	else
		__gtmp_2 = 0;
	return __gtmp_2;

};

static otawa_target_t otawa_target_LSLSS_W_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRDS_S__S___LT_SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRDS_S__S___LT_SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STREXHS_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STREXBS_S__S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STREXBS_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STREXS_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDREXHS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDREXBS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDREXBS_S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDREXS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STMSS_SS___LB_SSSSSSSSSSSSSSS_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSHS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSHS_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSBS_S___LT_PC_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSBS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSBS_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRBS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRBS_W_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRBS_S___LT_SS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRBS_W_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRS_W_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDMSS_W_SS___LB_SSSSSSSSSSSSSSS_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRHS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRHS_W_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRHS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRHS_W_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSHS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRHS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRHS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRS_W_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSHTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSBTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRHTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRHTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRBTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRBTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSBS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRBS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRBS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDC2SS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDC2SS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDC2SS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDC2SS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDCSS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDCSS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDCSS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDCSS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STC2SS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STC2SS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STC2SS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STC2SS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STCSS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STCSS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STCSS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STCSS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BLXS_0X08X(arm_inst_t *inst) {
	return (((int32_t)(((ARM_BLXS_0X08X___IADDR & ~(4 - 1)) + 4))) + __ARM_EXTS32(7, ((int32_t)(arm_concat32(arm_concat32(arm_concat16(arm_concat8(arm_concat8(ARM_BLXS_0X08X_i_x_S, __ARM_MASK32(1, ~(ARM_BLXS_0X08X_i_x_J1 ^ ARM_BLXS_0X08X_i_x_S)), 1, 1), __ARM_MASK32(1, ~(ARM_BLXS_0X08X_i_x_J2 ^ ARM_BLXS_0X08X_i_x_S)), 2, 1), ARM_BLXS_0X08X_i_x_imm10H, 3, 10), ARM_BLXS_0X08X_i_x_imm10L, 13, 10), 0, 23, 2)))));

};

static otawa_target_t otawa_target_TBBS__LT_S__S_RT_(arm_inst_t *inst) {
	return 0;

};

static otawa_target_t otawa_target_BLS_0XX(arm_inst_t *inst) {
	return (((int32_t)((ARM_BLS_0XX___IADDR + 4))) + __ARM_EXTS32(7, ((int32_t)(arm_concat32(arm_concat32(arm_concat16(arm_concat8(arm_concat8(ARM_BLS_0XX_i_x_S_set, __ARM_MASK32(1, ~(ARM_BLS_0XX_i_x_J1 ^ ARM_BLS_0XX_i_x_S_set)), 1, 1), __ARM_MASK32(1, ~(ARM_BLS_0XX_i_x_J2 ^ ARM_BLS_0XX_i_x_S_set)), 2, 1), ARM_BLS_0XX_i_x_imm10, 3, 10), ARM_BLS_0XX_i_x_imm11, 13, 11), arm_bit32(0, 0), 24, 1)))));

};

static otawa_target_t otawa_target_VSS_F64_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VSS_F32_SD__SD__SD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VSS_F32_QD__QD__QD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VSS_F32_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VPOPS__LB_SD_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VPOPS__LB_DD_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VADDS_F64_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VADDS_F32_SD__SD__SD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VADDS_F32_QD__QD__QD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VADDS_F32_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VCVTS_F64_S_DD__SD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VCVTSS_U32_F64_SD__DD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VCVTS_F32_S_SD__SD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VPUSHS__LB_SD_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VPUSHS__LB_DD_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMULS_F64_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMULS_F32_SD__SD__SD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMULS_F32_QD__QD__QD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMULS_F32_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMRSS_S__FPSCR(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VSTRS_SD___LT_S___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VSTRS_DD___LT_S___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VLDRS_DD___LT_S___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VLDRS_DD___LT_S___ISD_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VDIVS_F64_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VDIVS_F32_SD__SD__SD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VSUBS_F64_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VSUBS_F32_SD__SD__SD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMOVS_DD__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMOVS_SD__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMOVS_F64_DD__DD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMOVS_F32_SD__SD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMOVS_F64_DD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMOVS_F32_SD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UXTHS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UXTBS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_YIELDS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MOVS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MOVS_RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TSTS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SXTHS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SXTBS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBS_RD__RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBS_SP___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBS_RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBS_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRHS_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRHS_RD___LT_RD___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRBS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRBS_RD___LT_RD___ID_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRS_RD___LT_SP___ID_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRS_RD___LT_RD___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STMIAS_RD_21___LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SBCS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RORS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_REVSHS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_REV16S_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_REVS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_PUSHS__LB_SS_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_PUSHS__LB_SS_RB__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_POPS__LB_SS_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_POPS__LB_SS_RB__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORRS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RSBS_RD__RD___I0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MVNS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LSRS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LSRS_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LSLS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LSLS_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSHS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSBS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRHS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRHS_RD___LT_RD___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRBS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRBS_RD___LT_RD___ID_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRS_RD___LT_SP___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRS_RD___LT_PC___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRS_RD___LT_RD___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDMIAS_RD___LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EORS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMPS_RD__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMPS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMPS_RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMNS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CBZS_RD__D(arm_inst_t *inst) {
	return ((ARM_CBZS_RD__D___IADDR + 4) + ((uint32_t)(arm_concat8(arm_concat8(ARM_CBZS_RD__D_i_x_i, ARM_CBZS_RD__D_i_x_imm5, 1, 5), 0, 6, 1))));

};

static otawa_target_t otawa_target_BXS_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BLXS_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BKPT__ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BICS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BS_N__40(arm_inst_t *inst) {
	return (((int32_t)((ARM_BS_N__40___IADDR + 4))) + __ARM_EXTS16(20, ((int32_t)(arm_concat16(ARM_BS_N__40_i_x_imm11, arm_bit32(0, 0), 11, 1)))));

};

static otawa_target_t otawa_target_S_N_08X(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((ARM_S_N_08X_i_x_cond == 15))
		__gtmp_0 = 0;
	else
		__gtmp_0 = ((ARM_S_N_08X___IADDR + 4) + (((int32_t)(ARM_S_N_08X_i_x_simm_n)) << 1));
	return __gtmp_0;

};

static otawa_target_t otawa_target_ASRS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ASRS_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ANDS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDS_RD__RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDS_SP__SP___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDS_RD__SP___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDS_RD__PC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDS_RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDS_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADCS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MRCS_D__D__S__CRD__CRD__D(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDCSSS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDCSSS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDCSSS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDCSSS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STCSSS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STCSSS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STCSSS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STCSSS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VSTRS_SD___LT_S___ISD_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VSTRS_DD___LT_S___ISD_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VSTMSSS_SS___LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VSTMSSS_SS___LB_S_RB__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VSTMSSS_SS___LB_S_RB__1(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VSTMSSS_SS___LB_S_RB__2(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMULS_F64_DD__DD__DD_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMULS_F32_SD__SD__SD_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMUL_F32_QD__QD__QD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMUL_F32_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMOVS_DD__S__S_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMOVS_SD__S_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMOVS_F64_DD__DD_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMOVS_F32_SD__SD_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMOVS_F64_DD___ID_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VMOVS_F32_SD___ID_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VSS_F64_DD__DD__DD_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VSS_F32_SD__SD__SD_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VS_F32_QD__QD__QD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VS_F32_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VLDRS_DD___LT_S___ISD_RT__1(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VLDRS_DD___LT_S___ISD_RT__2(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VLDMDBS_S_21___LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VLDMIAS_SS___LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VLDMDBS_S_21___LB_S_RB__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VLDMIAS_SS___LB_S_RB__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VDIVS_F64_DD__DD__DD_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VDIVS_F32_SD__SD__SD_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VCVT_FD_FD_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VCVTSS_S_S_S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VADDS_F64_DD__DD__DD_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VADDS_F32_SD__SD__SD_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VADD_F32_QD__QD__QD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_VADD_F32_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DMB_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MRSS_S__CPSR(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MRSS_S__SPSR(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR___S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FSXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_SXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FSX__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_XC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_SC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_SX__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_F__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FX__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FS__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_C__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_X__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_F__S_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR___S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FSXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_SXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FSX__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_XC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_SC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_SX__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_F__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FX__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FS__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_C__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_X__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_F__S_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR____ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FSXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_SXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FSX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_XC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_SC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_SX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_F___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FS___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_C___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_X___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_F___ID_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR____ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FSXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_SXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FSX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_XC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_SC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_SX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_F___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FS___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_C___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_X___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_F___ID_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CDPSS_D__D__D__D__D__D(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BFIS_S___ID___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CLZS_S__S_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SWPS_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SWPSB_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UMLALSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SMLALSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UMULLSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SMULLSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MLASS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SWIS_D(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDMSS_SS___LB_S_RB_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STMSS_SS___LB_S_RB_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STREXHS_S__S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STREXDS_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STREXBS_S__S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STREXS_S__S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDREXHS_S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDREXDS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDREXBS_S___LT_S_RT__1(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDREXS_S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRDS_S___LT_SS__S_IUSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSSH_S___LT_SS__SSSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSSH_S___LT_SS__S_IUSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSSB_S___LT_SS__SSSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSSB_S___LT_SS__S_IUSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSH_S___LT_SS__SSSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSH_S___LT_SS__S_IUSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRHS_S___LT_SS__SSSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRHS_S___LT_SS__S_IUSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRSSS_S___LT_SS__SS__S__IDSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSSS_S___LT_SS__SS__S__IDSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRSSS_S___LT_SS__S_IDSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSSS_S___LT_SS__S_IDSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BSS__40(arm_inst_t *inst) {
	uint8_t __gtmp_0;
	if((ARM_BSS__40_x_cond_cond == 15))
		__gtmp_0 = ARM_BSS__40_x_setl;
	else
		__gtmp_0 = 0;
	return __ARM_MASK64(34, (((uint64_t)((ARM_BSS__40___IADDR + 8))) + arm_concat64(arm_concat64(((int32_t)(ARM_BSS__40_x_signed_immed_24_n)), __gtmp_0, 32, 1), 0, 33, 1)));

};

static otawa_target_t otawa_target_BLXS_S_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BXS_S_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MOVS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MOVTS_S___ID_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TSTS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TSTS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TSTS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TEQS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TEQS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TEQS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SBCSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SBCSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SBCSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RSCSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RSCSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RSCSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RSBSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RSBSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RSBSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORRSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORRSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORRSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MVNSS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MVNSS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MVNSS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MOVSS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MOVSS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MOVSS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EORSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EORSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EORSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMPS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMPS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMPS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMNS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMNS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMNS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BICSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BICSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BICSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ANDSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ANDSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ANDSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADCSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADCSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADCSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDSS_S__S___ID(arm_inst_t *inst) {
return 0;
};




/* function table */
static target_fun_t arm_target_table[] =
{
	otawa_target_UNKNOWN,
	otawa_target_UXTAHS_S__S__SS,
	otawa_target_UXTAB16S_S__S__SS,
	otawa_target_UXTABS_S__S__SS,
	otawa_target_USUB8S_S__S__S,
	otawa_target_USUB16S_S__S__S,
	otawa_target_USAXS_S__S__S,
	otawa_target_USATS_S___ID__SS,
	otawa_target_USADA8S_S__S__S__S,
	otawa_target_UQSUB8S_S__S__S,
	otawa_target_UQSUB16S_S__S__S,
	otawa_target_UQSAXS_S__S__S,
	otawa_target_UQASXS_S__S__S,
	otawa_target_UQADD8S_S__S__S,
	otawa_target_UQADD16S_S__S__S,
	otawa_target_UMULLS_S__S__S__S,
	otawa_target_UMLALS_S__S__S__S,
	otawa_target_UMAALS_S__S__S__S,
	otawa_target_UHSUB8S_S__S__S,
	otawa_target_UHSUB16S_S__S__S,
	otawa_target_UHSAXS_S__S__S,
	otawa_target_UHASXS_S__S__S,
	otawa_target_UHADD8S_S__S__S,
	otawa_target_UHADD16S_S__S__S,
	otawa_target_UDIVS_S__S__S,
	otawa_target_UBFXS_S__S___ID___ID,
	otawa_target_UASXS_S__S__S,
	otawa_target_UADD8S_S__S__S,
	otawa_target_UADD16S_S__S__S,
	otawa_target_SXTAHS_S__S__SS,
	otawa_target_SXTAB16S_S__S__SS,
	otawa_target_SXTABS_S__S__SS,
	otawa_target_SUBSS_W_S__S__SS,
	otawa_target_SUBWS_S__S___ID_,
	otawa_target_SUBSS_W_S__S___IU,
	otawa_target_SSUB8S_S__S__S,
	otawa_target_SSUB16S_S__S__S,
	otawa_target_SSAXS_S__S__S,
	otawa_target_SSATS_S___ID__SS,
	otawa_target_SMULLS_S__S__S__S,
	otawa_target_SMMLSSS_S__S__S__S,
	otawa_target_SMMLASS_S__S__S__S,
	otawa_target_SMLSLDSS_S__S__S__S,
	otawa_target_SMLSDSS_S__S__S__S,
	otawa_target_SMLAWSS_S__S__S__S,
	otawa_target_SMLALDSS_S__S__S__S,
	otawa_target_SMLALSSS_S__S__S__S,
	otawa_target_SMLALS_S__S__S__S,
	otawa_target_SMLADSS_S__S__S__S,
	otawa_target_SMLASSS_S__S__S__S,
	otawa_target_SHSUB8S_S__S__S,
	otawa_target_SHSUB16S_S__S__S,
	otawa_target_SHSAXS_S__S__S,
	otawa_target_SHASXS_S__S__S,
	otawa_target_SHADD8S_S__S__S,
	otawa_target_SHADD16S_S__S__S,
	otawa_target_SELS_S__S__S,
	otawa_target_SDIVS_S__S__S,
	otawa_target_SBFXS_S__S___ID___ID,
	otawa_target_SBCSS_W_S__S__SS,
	otawa_target_SBCSS_W_S__S___IU,
	otawa_target_SASXS_S__S__S,
	otawa_target_SADD8S_S__S__S,
	otawa_target_SADD16S_S__S__S,
	otawa_target_RSBSS_S__S__SS,
	otawa_target_RORSS_W_S__S__S,
	otawa_target_REVSHS_W_S__S,
	otawa_target_REV16S_W_S__S,
	otawa_target_REVS_W_S__S,
	otawa_target_RBITS_S__S,
	otawa_target_QSUB8S_S__S__S,
	otawa_target_QSUB16S_S__S__S,
	otawa_target_QSUBS_S__S__S,
	otawa_target_QSAXS_S__S__S,
	otawa_target_QDSUBS_S__S__S,
	otawa_target_QDADDS_S__S__S,
	otawa_target_QASXS_S__S__S,
	otawa_target_QADD8S_S__S__S,
	otawa_target_QADD16S_S__S__S,
	otawa_target_QADDS_S__S__S,
	otawa_target_PKHBTS_S__S__SS,
	otawa_target_ORNSS_S__S__SS,
	otawa_target_ORNSS_S__S___IU,
	otawa_target_MRRCSS_D__D__S__S__CRD,
	otawa_target_MRCSS_D__D__S__CRD__CRD___LB_D_RB_,
	otawa_target_MLSS_S__S__S__S,
	otawa_target_MLAS_S__S__S__S,
	otawa_target_MCRRSS_D__D__S__S__CRD,
	otawa_target_MCRSS_D__D__S__CRD__CRD___LB_D_RB_,
	otawa_target_LSRSS_W_S__S__S,
	otawa_target_LDMDBS_SS___LB_S_RB_,
	otawa_target_EORSS_W_S__S__SS,
	otawa_target_EORSS_W_S__S___IU,
	otawa_target_CLZS_S__S,
	otawa_target_CDPSS_D__D__CRD__CRD__CRD___LB_D_RB_,
	otawa_target_BICSS_W_S__S__SS,
	otawa_target_BICSS_W_S__S___IU,
	otawa_target_BFIS_S__S___ID___ID,
	otawa_target_BS_W_08X,
	otawa_target_BS_W_08X_0,
	otawa_target_MOVTS_S___ID,
	otawa_target_ORRS_W_S__S__SS,
	otawa_target_MOVWS_S___ID,
	otawa_target_ORRSS_W_S__S___IU,
	otawa_target_ASRSS_W_S__S__S,
	otawa_target_ANDSS_W_S__S__SS,
	otawa_target_ANDSS_W_S__S___IU,
	otawa_target_ADDSS_W_S__S__SS,
	otawa_target_ADDWS_S__S___ID_,
	otawa_target_ADDSS_W_S__S___IU,
	otawa_target_ADCSS_W_S__S__SS,
	otawa_target_ADCSS_W_S__S___IU,
	otawa_target_PLIS__LT_S__S_RT_,
	otawa_target_PLIS__LT_PC_RT_,
	otawa_target_PLIS__LT_S_RT_,
	otawa_target_PLIS__LT_S_RT__0,
	otawa_target_PLDSS__LT_S__S_RT_,
	otawa_target_PLDSS__LT_S_RT_,
	otawa_target_PLDSS__LT_S_RT__0,
	otawa_target_RSBSS_W_S__S___ID,
	otawa_target_LSLSS_W_S__S__S,
	otawa_target_LDRDS_S__S___LT_SS,
	otawa_target_STRDS_S__S___LT_SS,
	otawa_target_STREXHS_S__S___LT_S_RT_,
	otawa_target_STREXBS_S__S__S___LT_S_RT_,
	otawa_target_STREXBS_S__S___LT_S_RT_,
	otawa_target_STREXS_S__S___LT_S_RT_,
	otawa_target_LDREXHS_S___LT_S_RT_,
	otawa_target_LDREXBS_S___LT_S_RT_,
	otawa_target_LDREXBS_S___LT_S_RT__0,
	otawa_target_LDREXS_S___LT_S_RT_,
	otawa_target_STMSS_SS___LB_SSSSSSSSSSSSSSS_RB_,
	otawa_target_LDRSHS_S___LT_S_RT____IS0XX,
	otawa_target_LDRSHS_S___LT_S___I0XX_RT_,
	otawa_target_LDRSBS_S___LT_PC_RT_,
	otawa_target_LDRSBS_S___LT_S_RT____IS0XX,
	otawa_target_LDRSBS_S___LT_S___I0XX_RT_,
	otawa_target_LDRBS_S___LT_S_RT____IS0XX,
	otawa_target_LDRBS_W_S___LT_S___I0XX_RT_,
	otawa_target_STRBS_S___LT_SS,
	otawa_target_STRBS_W_S___LT_S___I0XX_RT_,
	otawa_target_STRS_S___LT_S_RT____IS0XX,
	otawa_target_STRS_W_S___LT_S___I0XX_RT_,
	otawa_target_LDMSS_W_SS___LB_SSSSSSSSSSSSSSS_RB_,
	otawa_target_STRHS_S___LT_S_RT____IS0XX,
	otawa_target_STRHS_W_S___LT_S_RT_,
	otawa_target_LDRHS_S___LT_S_RT____IS0XX,
	otawa_target_LDRHS_W_S___LT_S_RT_,
	otawa_target_LDRSHS_W_S___LT_S__S_RT_,
	otawa_target_STRHS_W_S___LT_S__S_RT_,
	otawa_target_LDRHS_W_S___LT_S__S_RT_,
	otawa_target_LDRS_S___LT_S_RT____IS0XX,
	otawa_target_LDRS_W_S___LT_S___I0XX_RT_,
	otawa_target_LDRSHTS_S___LT_S_RT_,
	otawa_target_LDRSBTS_S___LT_S_RT_,
	otawa_target_STRTS_S___LT_S_RT_,
	otawa_target_LDRTS_S___LT_S_RT_,
	otawa_target_STRHTS_S___LT_S_RT_,
	otawa_target_LDRHTS_S___LT_S_RT_,
	otawa_target_STRBTS_S___LT_S_RT_,
	otawa_target_LDRBTS_S___LT_S_RT_,
	otawa_target_LDRSBS_W_S___LT_S__S_RT_,
	otawa_target_STRBS_W_S___LT_S__S_RT_,
	otawa_target_LDRBS_W_S___LT_S__S_RT_,
	otawa_target_STRS_W_S___LT_S__S_RT_,
	otawa_target_LDRS_W_S___LT_S__S_RT_,
	otawa_target_LDC2SS_D__D___LT_RD_RT___D,
	otawa_target_LDC2SS_D__D___LT_RD_RT____ISD,
	otawa_target_LDC2SS_D__D___LT_RD___ISD_RT__21,
	otawa_target_LDC2SS_D__D___LT_RD___ISD_RT_,
	otawa_target_LDCSS_D__D___LT_RD_RT___D,
	otawa_target_LDCSS_D__D___LT_RD_RT____ISD,
	otawa_target_LDCSS_D__D___LT_RD___ISD_RT__21,
	otawa_target_LDCSS_D__D___LT_RD___ISD_RT_,
	otawa_target_STC2SS_D__D___LT_RD_RT___D,
	otawa_target_STC2SS_D__D___LT_RD_RT____ISD,
	otawa_target_STC2SS_D__D___LT_RD___ISD_RT__21,
	otawa_target_STC2SS_D__D___LT_RD___ISD_RT_,
	otawa_target_STCSS_D__D___LT_RD_RT___D,
	otawa_target_STCSS_D__D___LT_RD_RT____ISD,
	otawa_target_STCSS_D__D___LT_RD___ISD_RT__21,
	otawa_target_STCSS_D__D___LT_RD___ISD_RT_,
	otawa_target_BLXS_0X08X,
	otawa_target_TBBS__LT_S__S_RT_,
	otawa_target_BLS_0XX,
	otawa_target_VSS_F64_DD__DD__DD,
	otawa_target_VSS_F32_SD__SD__SD,
	otawa_target_VSS_F32_QD__QD__QD,
	otawa_target_VSS_F32_DD__DD__DD,
	otawa_target_VPOPS__LB_SD_RB_,
	otawa_target_VPOPS__LB_DD_RB_,
	otawa_target_VADDS_F64_DD__DD__DD,
	otawa_target_VADDS_F32_SD__SD__SD,
	otawa_target_VADDS_F32_QD__QD__QD,
	otawa_target_VADDS_F32_DD__DD__DD,
	otawa_target_VCVTS_F64_S_DD__SD,
	otawa_target_VCVTSS_U32_F64_SD__DD,
	otawa_target_VCVTS_F32_S_SD__SD,
	otawa_target_VPUSHS__LB_SD_RB_,
	otawa_target_VPUSHS__LB_DD_RB_,
	otawa_target_VMULS_F64_DD__DD__DD,
	otawa_target_VMULS_F32_SD__SD__SD,
	otawa_target_VMULS_F32_QD__QD__QD,
	otawa_target_VMULS_F32_DD__DD__DD,
	otawa_target_VMRSS_S__FPSCR,
	otawa_target_VSTRS_SD___LT_S___ISD_RT_,
	otawa_target_VSTRS_DD___LT_S___ISD_RT_,
	otawa_target_VLDRS_DD___LT_S___ISD_RT_,
	otawa_target_VLDRS_DD___LT_S___ISD_RT__0,
	otawa_target_VDIVS_F64_DD__DD__DD,
	otawa_target_VDIVS_F32_SD__SD__SD,
	otawa_target_VSUBS_F64_DD__DD__DD,
	otawa_target_VSUBS_F32_SD__SD__SD,
	otawa_target_VMOVS_DD__S__S,
	otawa_target_VMOVS_SD__S,
	otawa_target_VMOVS_F64_DD__DD,
	otawa_target_VMOVS_F32_SD__SD,
	otawa_target_VMOVS_F64_DD___ID,
	otawa_target_VMOVS_F32_SD___ID,
	otawa_target_UXTHS_RD__RD,
	otawa_target_UXTBS_RD__RD,
	otawa_target_YIELDS,
	otawa_target_MOVS_S__S,
	otawa_target_MOVS_RD___ID,
	otawa_target_TSTS_RD__RD,
	otawa_target_SXTHS_RD__RD,
	otawa_target_SXTBS_RD__RD,
	otawa_target_SUBS_RD__RD__RD,
	otawa_target_SUBS_SP___ID,
	otawa_target_SUBS_RD___ID,
	otawa_target_SUBS_RD__RD___ID,
	otawa_target_STRHS_RD___LT_RD__RD__RT_,
	otawa_target_STRHS_RD___LT_RD___I0XX_RT_,
	otawa_target_STRBS_RD___LT_RD__RD_RT_,
	otawa_target_STRBS_RD___LT_RD___ID_RT_,
	otawa_target_STRS_RD___LT_SP___ID_RT_,
	otawa_target_STRS_RD___LT_RD__RD_RT_,
	otawa_target_STRS_RD___LT_RD___I0XX_RT_,
	otawa_target_STMIAS_RD_21___LB_S_RB_,
	otawa_target_SBCS_RD__RD,
	otawa_target_RORS_RD__RD,
	otawa_target_REVSHS_RD__RD,
	otawa_target_REV16S_RD__RD,
	otawa_target_REVS_RD__RD,
	otawa_target_PUSHS__LB_SS_RB_,
	otawa_target_PUSHS__LB_SS_RB__0,
	otawa_target_POPS__LB_SS_RB_,
	otawa_target_POPS__LB_SS_RB__0,
	otawa_target_ORRS_RD__RD,
	otawa_target_RSBS_RD__RD___I0,
	otawa_target_MVNS_RD__RD,
	otawa_target_MULS_RD__RD,
	otawa_target_LSRS_RD__RD,
	otawa_target_LSRS_RD__RD___ID,
	otawa_target_LSLS_RD__RD,
	otawa_target_LSLS_RD__RD___ID,
	otawa_target_LDRSHS_RD___LT_RD__RD_RT_,
	otawa_target_LDRSBS_RD___LT_RD__RD_RT_,
	otawa_target_LDRHS_RD___LT_RD__RD_RT_,
	otawa_target_LDRHS_RD___LT_RD___I0XX_RT_,
	otawa_target_LDRBS_RD___LT_RD__RD_RT_,
	otawa_target_LDRBS_RD___LT_RD___ID_RT_,
	otawa_target_LDRS_RD___LT_SP___I0XX_RT_,
	otawa_target_LDRS_RD___LT_PC___I0XX_RT_,
	otawa_target_LDRS_RD___LT_RD__RD_RT_,
	otawa_target_LDRS_RD___LT_RD___I0XX_RT_,
	otawa_target_LDMIAS_RD___LB_S_RB_,
	otawa_target_EORS_RD__RD,
	otawa_target_CMPS_RD__S,
	otawa_target_CMPS_RD__RD,
	otawa_target_CMPS_RD___ID,
	otawa_target_CMNS_RD__RD,
	otawa_target_CBZS_RD__D,
	otawa_target_BXS_S,
	otawa_target_BLXS_S,
	otawa_target_BKPT__ID,
	otawa_target_BICS_RD__RD,
	otawa_target_BS_N__40,
	otawa_target_S_N_08X,
	otawa_target_ASRS_RD__RD,
	otawa_target_ASRS_RD__RD___ID,
	otawa_target_ANDS_RD__RD,
	otawa_target_ADDS_S__S,
	otawa_target_ADDS_RD__RD__RD,
	otawa_target_ADDS_SP__SP___ID,
	otawa_target_ADDS_RD__SP___ID,
	otawa_target_ADDS_RD__PC___ID,
	otawa_target_ADDS_RD___ID,
	otawa_target_ADDS_RD__RD___ID,
	otawa_target_ADCS_RD__RD,
	otawa_target_MRCS_D__D__S__CRD__CRD__D,
	otawa_target_LDCSSS_D__D___LT_RD_RT___D,
	otawa_target_LDCSSS_D__D___LT_RD_RT____ISD,
	otawa_target_LDCSSS_D__D___LT_RD___ISD_RT__21,
	otawa_target_LDCSSS_D__D___LT_RD___ISD_RT_,
	otawa_target_STCSSS_D__D___LT_RD_RT___D,
	otawa_target_STCSSS_D__D___LT_RD_RT____ISD,
	otawa_target_STCSSS_D__D___LT_RD___ISD_RT__21,
	otawa_target_STCSSS_D__D___LT_RD___ISD_RT_,
	otawa_target_VSTRS_SD___LT_S___ISD_RT__0,
	otawa_target_VSTRS_DD___LT_S___ISD_RT__0,
	otawa_target_VSTMSSS_SS___LB_S_RB_,
	otawa_target_VSTMSSS_SS___LB_S_RB__0,
	otawa_target_VSTMSSS_SS___LB_S_RB__1,
	otawa_target_VSTMSSS_SS___LB_S_RB__2,
	otawa_target_VMULS_F64_DD__DD__DD_0,
	otawa_target_VMULS_F32_SD__SD__SD_0,
	otawa_target_VMUL_F32_QD__QD__QD,
	otawa_target_VMUL_F32_DD__DD__DD,
	otawa_target_VMOVS_DD__S__S_0,
	otawa_target_VMOVS_SD__S_0,
	otawa_target_VMOVS_F64_DD__DD_0,
	otawa_target_VMOVS_F32_SD__SD_0,
	otawa_target_VMOVS_F64_DD___ID_0,
	otawa_target_VMOVS_F32_SD___ID_0,
	otawa_target_VSS_F64_DD__DD__DD_0,
	otawa_target_VSS_F32_SD__SD__SD_0,
	otawa_target_VS_F32_QD__QD__QD,
	otawa_target_VS_F32_DD__DD__DD,
	otawa_target_VLDRS_DD___LT_S___ISD_RT__1,
	otawa_target_VLDRS_DD___LT_S___ISD_RT__2,
	otawa_target_VLDMDBS_S_21___LB_S_RB_,
	otawa_target_VLDMIAS_SS___LB_S_RB_,
	otawa_target_VLDMDBS_S_21___LB_S_RB__0,
	otawa_target_VLDMIAS_SS___LB_S_RB__0,
	otawa_target_VDIVS_F64_DD__DD__DD_0,
	otawa_target_VDIVS_F32_SD__SD__SD_0,
	otawa_target_VCVT_FD_FD_S__S,
	otawa_target_VCVTSS_S_S_S_S,
	otawa_target_VADDS_F64_DD__DD__DD_0,
	otawa_target_VADDS_F32_SD__SD__SD_0,
	otawa_target_VADD_F32_QD__QD__QD,
	otawa_target_VADD_F32_DD__DD__DD,
	otawa_target_DMB_S,
	otawa_target_MRSS_S__CPSR,
	otawa_target_MRSS_S__SPSR,
	otawa_target_MSRS_CPSR___S,
	otawa_target_MSRS_CPSR_FSXC__S,
	otawa_target_MSRS_CPSR_SXC__S,
	otawa_target_MSRS_CPSR_FXC__S,
	otawa_target_MSRS_CPSR_FSX__S,
	otawa_target_MSRS_CPSR_XC__S,
	otawa_target_MSRS_CPSR_SC__S,
	otawa_target_MSRS_CPSR_SX__S,
	otawa_target_MSRS_CPSR_F__S,
	otawa_target_MSRS_CPSR_FX__S,
	otawa_target_MSRS_CPSR_FS__S,
	otawa_target_MSRS_CPSR_C__S,
	otawa_target_MSRS_CPSR_X__S,
	otawa_target_MSRS_CPSR_S__S,
	otawa_target_MSRS_CPSR_F__S_0,
	otawa_target_MSRS_SPSR___S,
	otawa_target_MSRS_SPSR_FSXC__S,
	otawa_target_MSRS_SPSR_SXC__S,
	otawa_target_MSRS_SPSR_FXC__S,
	otawa_target_MSRS_SPSR_FSX__S,
	otawa_target_MSRS_SPSR_XC__S,
	otawa_target_MSRS_SPSR_SC__S,
	otawa_target_MSRS_SPSR_SX__S,
	otawa_target_MSRS_SPSR_F__S,
	otawa_target_MSRS_SPSR_FX__S,
	otawa_target_MSRS_SPSR_FS__S,
	otawa_target_MSRS_SPSR_C__S,
	otawa_target_MSRS_SPSR_X__S,
	otawa_target_MSRS_SPSR_S__S,
	otawa_target_MSRS_SPSR_F__S_0,
	otawa_target_MSRS_CPSR____ID,
	otawa_target_MSRS_CPSR_FSXC___ID,
	otawa_target_MSRS_CPSR_SXC___ID,
	otawa_target_MSRS_CPSR_FXC___ID,
	otawa_target_MSRS_CPSR_FSX___ID,
	otawa_target_MSRS_CPSR_XC___ID,
	otawa_target_MSRS_CPSR_SC___ID,
	otawa_target_MSRS_CPSR_SX___ID,
	otawa_target_MSRS_CPSR_F___ID,
	otawa_target_MSRS_CPSR_FX___ID,
	otawa_target_MSRS_CPSR_FS___ID,
	otawa_target_MSRS_CPSR_C___ID,
	otawa_target_MSRS_CPSR_X___ID,
	otawa_target_MSRS_CPSR_S___ID,
	otawa_target_MSRS_CPSR_F___ID_0,
	otawa_target_MSRS_SPSR____ID,
	otawa_target_MSRS_SPSR_FSXC___ID,
	otawa_target_MSRS_SPSR_SXC___ID,
	otawa_target_MSRS_SPSR_FXC___ID,
	otawa_target_MSRS_SPSR_FSX___ID,
	otawa_target_MSRS_SPSR_XC___ID,
	otawa_target_MSRS_SPSR_SC___ID,
	otawa_target_MSRS_SPSR_SX___ID,
	otawa_target_MSRS_SPSR_F___ID,
	otawa_target_MSRS_SPSR_FX___ID,
	otawa_target_MSRS_SPSR_FS___ID,
	otawa_target_MSRS_SPSR_C___ID,
	otawa_target_MSRS_SPSR_X___ID,
	otawa_target_MSRS_SPSR_S___ID,
	otawa_target_MSRS_SPSR_F___ID_0,
	otawa_target_CDPSS_D__D__D__D__D__D,
	otawa_target_BFIS_S___ID___ID,
	otawa_target_CLZS_S__S_0,
	otawa_target_SWPS_S__S___LT_S_RT_,
	otawa_target_SWPSB_S__S___LT_S_RT_,
	otawa_target_UMLALSS_S__S__S__S,
	otawa_target_SMLALSS_S__S__S__S,
	otawa_target_UMULLSS_S__S__S__S,
	otawa_target_SMULLSS_S__S__S__S,
	otawa_target_MULSS_S__S__S,
	otawa_target_MLASS_S__S__S__S,
	otawa_target_SWIS_D,
	otawa_target_LDMSS_SS___LB_S_RB_S,
	otawa_target_STMSS_SS___LB_S_RB_S,
	otawa_target_STREXHS_S__S___LT_S_RT__0,
	otawa_target_STREXDS_S__S___LT_S_RT_,
	otawa_target_STREXBS_S__S___LT_S_RT__0,
	otawa_target_STREXS_S__S___LT_S_RT__0,
	otawa_target_LDREXHS_S___LT_S_RT__0,
	otawa_target_LDREXDS_S___LT_S_RT_,
	otawa_target_LDREXBS_S___LT_S_RT__1,
	otawa_target_LDREXS_S___LT_S_RT__0,
	otawa_target_STRDS_S___LT_SS__S_IUSS,
	otawa_target_LDRSSH_S___LT_SS__SSSS,
	otawa_target_LDRSSH_S___LT_SS__S_IUSS,
	otawa_target_LDRSSB_S___LT_SS__SSSS,
	otawa_target_LDRSSB_S___LT_SS__S_IUSS,
	otawa_target_LDRSH_S___LT_SS__SSSS,
	otawa_target_LDRSH_S___LT_SS__S_IUSS,
	otawa_target_STRHS_S___LT_SS__SSSS,
	otawa_target_STRHS_S___LT_SS__S_IUSS,
	otawa_target_STRSSS_S___LT_SS__SS__S__IDSS,
	otawa_target_LDRSSS_S___LT_SS__SS__S__IDSS,
	otawa_target_STRSSS_S___LT_SS__S_IDSS,
	otawa_target_LDRSSS_S___LT_SS__S_IDSS,
	otawa_target_BSS__40,
	otawa_target_BLXS_S_0,
	otawa_target_BXS_S_0,
	otawa_target_MOVS_S___ID,
	otawa_target_MOVTS_S___ID_0,
	otawa_target_TSTS_S___ID,
	otawa_target_TSTS_S__S__S_S,
	otawa_target_TSTS_S__S,
	otawa_target_TEQS_S___ID,
	otawa_target_TEQS_S__S__S_S,
	otawa_target_TEQS_S__S,
	otawa_target_SUBSS_S__S___ID,
	otawa_target_SUBSS_S__S__S__S_S,
	otawa_target_SUBSS_S__S__S,
	otawa_target_SBCSS_S__S___ID,
	otawa_target_SBCSS_S__S__S__S_S,
	otawa_target_SBCSS_S__S__S,
	otawa_target_RSCSS_S__S___ID,
	otawa_target_RSCSS_S__S__S__S_S,
	otawa_target_RSCSS_S__S__S,
	otawa_target_RSBSS_S__S___ID,
	otawa_target_RSBSS_S__S__S__S_S,
	otawa_target_RSBSS_S__S__S,
	otawa_target_ORRSS_S__S___ID,
	otawa_target_ORRSS_S__S__S__S_S,
	otawa_target_ORRSS_S__S__S,
	otawa_target_MVNSS_S___ID,
	otawa_target_MVNSS_S__S__S_S,
	otawa_target_MVNSS_S__S,
	otawa_target_MOVSS_S___ID,
	otawa_target_MOVSS_S__S__S_S,
	otawa_target_MOVSS_S__S,
	otawa_target_EORSS_S__S___ID,
	otawa_target_EORSS_S__S__S__S_S,
	otawa_target_EORSS_S__S__S,
	otawa_target_CMPS_S___ID,
	otawa_target_CMPS_S__S__S_S,
	otawa_target_CMPS_S__S,
	otawa_target_CMNS_S___ID,
	otawa_target_CMNS_S__S__S_S,
	otawa_target_CMNS_S__S,
	otawa_target_BICSS_S__S___ID,
	otawa_target_BICSS_S__S__S__S_S,
	otawa_target_BICSS_S__S__S,
	otawa_target_ANDSS_S__S___ID,
	otawa_target_ANDSS_S__S__S__S_S,
	otawa_target_ANDSS_S__S__S,
	otawa_target_ADDSS_S__S__S__S_S,
	otawa_target_ADDSS_S__S__S,
	otawa_target_ADCSS_S__S___ID,
	otawa_target_ADCSS_S__S__S__S_S,
	otawa_target_ADCSS_S__S__S,
	otawa_target_ADDSS_S__S___ID
};



/**
 * Get the OTAWA target of the instruction.
 * @return OTAWA target.
 */
otawa_target_t arm_target(arm_inst_t *inst)
{
        return arm_target_table[inst->ident](inst);
}

#ifdef __cplusplus
}
#endif

