/* Generated by gliss-attr (118/04/09 13:06:19) copyright (c) 2009 IRIT - UPS */

#include <arm/api.h>
#include <arm/id.h>
#include <arm/macros.h>
#include <arm/grt.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef unsigned long otawa_kind_t;
typedef otawa_kind_t (*fun_t)(arm_inst_t *inst);

/*** function definition ***/

static otawa_kind_t otawa_kind_UNKNOWN(arm_inst_t *inst) {
	return 0;
}

static otawa_kind_t otawa_kind_UXTAHS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UXTAB16S_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UXTABS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_USUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_USUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_USAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_USATS_S___ID__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_USADA8S_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UQSUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UQSUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UQSAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UQASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UQADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UQADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UMULLS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UMLALS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UMAALS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UHSUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UHSUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UHSAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UHASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UHADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UHADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UDIVS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UBFXS_S__S___ID___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SXTAHS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SXTAB16S_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SXTABS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBWS_S__S___ID_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SSUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SSUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SSAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SSATS_S___ID__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SMULLS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SMMLSSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SMMLASS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SMLSLDSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SMLSDSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SMLAWSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SMLALDSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SMLALSSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SMLALS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SMLADSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SMLASSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SHSUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SHSUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SHSAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SHASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SHADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SHADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SELS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SDIVS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SBFXS_S__S___ID___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SBCSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SBCSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_RSBSS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_RORSS_W_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_REVSHS_W_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_REV16S_W_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_REVS_W_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_RBITS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_QSUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_QSUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_QSUBS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_QSAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_QDSUBS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_QDADDS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_QASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_QADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_QADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_QADDS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_PKHBTS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ORNSS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ORNSS_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MRRCSS_D__D__S__S__CRD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MRCSS_D__D__S__CRD__CRD___LB_D_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MLSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MLAS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MCRRSS_D__D__S__S__CRD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MCRSS_D__D__S__CRD__CRD___LB_D_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LSRSS_W_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDMDBS_SS___LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_EORSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_EORSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CLZS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CDPSS_D__D__CRD__CRD__CRD___LB_D_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_BICSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_BICSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_BFIS_S__S___ID___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_BS_W_08X(arm_inst_t *inst) {
	return 2;

};

static otawa_kind_t otawa_kind_BS_W_08X_0(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((arm_field8(ARM_BS_W_08X_0_i_x_cond_cond, 3, 1) == 7))
		__gtmp_1 = 0;
	else {
		if((((uint32_t)(ARM_BS_W_08X_0_i_x_cond_cond)) == 14))
			__gtmp_0 = 0;
		else
			__gtmp_0 = 1;
		__gtmp_1 = (2 | __gtmp_0);
	}
	return __gtmp_1;

};

static otawa_kind_t otawa_kind_MOVTS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ORRS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MOVWS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ORRSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ASRSS_W_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ANDSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ANDSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDWS_S__S___ID_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADCSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADCSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_PLIS__LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_PLIS__LT_PC_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_PLIS__LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_PLIS__LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_PLDSS__LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_PLDSS__LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_PLDSS__LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_RSBSS_W_S__S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(ARM_RSBSS_W_S__S___ID_i_x_Rd_r)) == 15))
		__gtmp_0 = 2;
	else
		__gtmp_0 = 0;
	return (((512LU | 128) | __gtmp_0) | 1073741824LU);

};

static otawa_kind_t otawa_kind_LSLSS_W_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRDS_S__S___LT_SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRDS_S__S___LT_SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STREXHS_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STREXBS_S__S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STREXBS_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STREXS_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDREXHS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDREXBS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDREXBS_S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDREXS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STMSS_SS___LB_SSSSSSSSSSSSSSS_RB_(arm_inst_t *inst) {
	return (((16 | 64) | 32768LU) | 128);

};

static otawa_kind_t otawa_kind_LDRSHS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRSHS_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRSBS_S___LT_PC_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRSBS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRSBS_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRBS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRBS_W_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRBS_S___LT_SS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRBS_W_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRS_W_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDMSS_W_SS___LB_SSSSSSSSSSSSSSS_RB_(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if(ARM_LDMSS_W_SS___LB_SSSSSSSSSSSSSSS_RB__i_x_register_list__P)
		__gtmp_0 = 2;
	else
		__gtmp_0 = 0;
	if(((((uint32_t)(ARM_LDMSS_W_SS___LB_SSSSSSSSSSSSSSS_RB__i_x_Rn_r)) == 13) && ARM_LDMSS_W_SS___LB_SSSSSSSSSSSSSSS_RB__i_x_register_list__P))
		__gtmp_1 = (2 | 8);
	else
		__gtmp_1 = 0;
	return (((((16 | 32) | 32768LU) | 128) | __gtmp_0) | __gtmp_1);

};

static otawa_kind_t otawa_kind_STRHS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRHS_W_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRHS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRHS_W_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRSHS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRHS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRHS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(ARM_LDRS_S___LT_S_RT____IS0XX_i_x_x_Rt_r)) == 15))
		__gtmp_0 = 2;
	else
		__gtmp_0 = 0;
	if(((((uint32_t)(ARM_LDRS_S___LT_S_RT____IS0XX_i_x_x_Rt_r)) == 15) && (((uint32_t)(ARM_LDRS_S___LT_S_RT____IS0XX_i_x_x_Rn_r)) == 13)))
		__gtmp_1 = 8;
	else
		__gtmp_1 = 0;
	return ((((16 | 128) | 32) | __gtmp_0) | __gtmp_1);

};

static otawa_kind_t otawa_kind_LDRS_W_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(ARM_LDRS_W_S___LT_S___I0XX_RT__i_x_x_Rt_r)) == 15))
		__gtmp_0 = 2;
	else
		__gtmp_0 = 0;
	if(((((uint32_t)(ARM_LDRS_W_S___LT_S___I0XX_RT__i_x_x_Rt_r)) == 15) && (((uint32_t)(ARM_LDRS_W_S___LT_S___I0XX_RT__i_x_x_Rn_r)) == 13)))
		__gtmp_1 = 8;
	else
		__gtmp_1 = 0;
	return ((((16 | 128) | 32) | __gtmp_0) | __gtmp_1);

};

static otawa_kind_t otawa_kind_LDRSHTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRSBTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRHTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRHTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRBTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRBTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRSBS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRBS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRBS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDC2SS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
	return ((16 | 128) | 32);

};

static otawa_kind_t otawa_kind_LDC2SS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
	return ((16 | 128) | 32);

};

static otawa_kind_t otawa_kind_LDC2SS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
	return ((16 | 128) | 32);

};

static otawa_kind_t otawa_kind_LDC2SS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
	return ((16 | 128) | 32);

};

static otawa_kind_t otawa_kind_LDCSS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
	return ((16 | 128) | 32);

};

static otawa_kind_t otawa_kind_LDCSS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
	return ((16 | 128) | 32);

};

static otawa_kind_t otawa_kind_LDCSS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
	return ((16 | 128) | 32);

};

static otawa_kind_t otawa_kind_LDCSS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
	return ((16 | 128) | 32);

};

static otawa_kind_t otawa_kind_STC2SS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
	return ((16 | 128) | 64);

};

static otawa_kind_t otawa_kind_STC2SS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
	return ((16 | 128) | 64);

};

static otawa_kind_t otawa_kind_STC2SS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
	return ((16 | 128) | 64);

};

static otawa_kind_t otawa_kind_STC2SS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
	return ((16 | 128) | 64);

};

static otawa_kind_t otawa_kind_STCSS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
	return ((16 | 128) | 64);

};

static otawa_kind_t otawa_kind_STCSS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
	return ((16 | 128) | 64);

};

static otawa_kind_t otawa_kind_STCSS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
	return ((16 | 128) | 64);

};

static otawa_kind_t otawa_kind_STCSS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
	return ((16 | 128) | 64);

};

static otawa_kind_t otawa_kind_BLXS_0X08X(arm_inst_t *inst) {
	return (2 | 4);

};

static otawa_kind_t otawa_kind_TBBS__LT_S__S_RT_(arm_inst_t *inst) {
	return ((2 | 16) | 32);

};

static otawa_kind_t otawa_kind_BLS_0XX(arm_inst_t *inst) {
	return (2 | 4);

};

static otawa_kind_t otawa_kind_VSS_F64_DD__DD__DD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VSS_F32_SD__SD__SD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VSS_F32_QD__QD__QD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VSS_F32_DD__DD__DD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VPOPS__LB_SD_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_VPOPS__LB_DD_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_VADDS_F64_DD__DD__DD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VADDS_F32_SD__SD__SD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VADDS_F32_QD__QD__QD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VADDS_F32_DD__DD__DD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VCVTS_F64_S_DD__SD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VCVTSS_U32_F64_SD__DD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VCVTS_F32_S_SD__SD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VPUSHS__LB_SD_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_VPUSHS__LB_DD_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_VMULS_F64_DD__DD__DD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VMULS_F32_SD__SD__SD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VMULS_F32_QD__QD__QD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VMULS_F32_DD__DD__DD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VMRSS_S__FPSCR(arm_inst_t *inst) {
	return ((512LU | 256LU) | 128);

};

static otawa_kind_t otawa_kind_VSTRS_SD___LT_S___ISD_RT_(arm_inst_t *inst) {
	return ((16 | 64) | 256LU);

};

static otawa_kind_t otawa_kind_VSTRS_DD___LT_S___ISD_RT_(arm_inst_t *inst) {
	return ((16 | 64) | 256LU);

};

static otawa_kind_t otawa_kind_VLDRS_DD___LT_S___ISD_RT_(arm_inst_t *inst) {
	return ((16 | 32) | 256LU);

};

static otawa_kind_t otawa_kind_VLDRS_DD___LT_S___ISD_RT__0(arm_inst_t *inst) {
	return ((16 | 32) | 256LU);

};

static otawa_kind_t otawa_kind_VDIVS_F64_DD__DD__DD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VDIVS_F32_SD__SD__SD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VSUBS_F64_DD__DD__DD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VSUBS_F32_SD__SD__SD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VMOVS_DD__S__S(arm_inst_t *inst) {
	return ((512LU | 256LU) | 128);

};

static otawa_kind_t otawa_kind_VMOVS_SD__S(arm_inst_t *inst) {
	return ((512LU | 256LU) | 128);

};

static otawa_kind_t otawa_kind_VMOVS_F64_DD__DD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VMOVS_F32_SD__SD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VMOVS_F64_DD___ID(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VMOVS_F32_SD___ID(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_UXTHS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UXTBS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_YIELDS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MOVS_S__S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if(((((uint32_t)(ARM_MOVS_S__S_i_x_H)) == 1) && (ARM_MOVS_S__S_i_x_rd_ro == 7))) {
		if((((uint32_t)(ARM_MOVS_S__S_i_x_rm_r)) == 14))
			__gtmp_0 = 8;
		else
			__gtmp_0 = 0;
		__gtmp_1 = (2 | __gtmp_0);
	}
	else
		__gtmp_1 = (512LU | 128);
	return __gtmp_1;

};

static otawa_kind_t otawa_kind_MOVS_RD___ID(arm_inst_t *inst) {
	return ((512LU | 128) | 1073741824LU);

};

static otawa_kind_t otawa_kind_TSTS_RD__RD(arm_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SXTHS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SXTBS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBS_RD__RD__RD(arm_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SUBS_SP___ID(arm_inst_t *inst) {
	return ((512LU | 128) | 1073741824LU);

};

static otawa_kind_t otawa_kind_SUBS_RD___ID(arm_inst_t *inst) {
	return ((512LU | 128) | 1073741824LU);

};

static otawa_kind_t otawa_kind_SUBS_RD__RD___ID(arm_inst_t *inst) {
	return ((512LU | 128) | 1073741824LU);

};

static otawa_kind_t otawa_kind_STRHS_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
	return ((16 | 64) | 128);

};

static otawa_kind_t otawa_kind_STRHS_RD___LT_RD___I0XX_RT_(arm_inst_t *inst) {
	return ((16 | 64) | 128);

};

static otawa_kind_t otawa_kind_STRBS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
	return ((16 | 64) | 128);

};

static otawa_kind_t otawa_kind_STRBS_RD___LT_RD___ID_RT_(arm_inst_t *inst) {
	return ((16 | 64) | 128);

};

static otawa_kind_t otawa_kind_STRS_RD___LT_SP___ID_RT_(arm_inst_t *inst) {
	return ((16 | 64) | 128);

};

static otawa_kind_t otawa_kind_STRS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
	return ((16 | 64) | 128);

};

static otawa_kind_t otawa_kind_STRS_RD___LT_RD___I0XX_RT_(arm_inst_t *inst) {
	return ((16 | 64) | 128);

};

static otawa_kind_t otawa_kind_STMIAS_RD_21___LB_S_RB_(arm_inst_t *inst) {
	return (((16 | 64) | 32768LU) | 128);

};

static otawa_kind_t otawa_kind_SBCS_RD__RD(arm_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_RORS_RD__RD(arm_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_REVSHS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_REV16S_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_REVS_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_PUSHS__LB_SS_RB_(arm_inst_t *inst) {
	return (((16 | 64) | 32768LU) | 128);

};

static otawa_kind_t otawa_kind_PUSHS__LB_SS_RB__0(arm_inst_t *inst) {
	return (((16 | 64) | 32768LU) | 128);

};

static otawa_kind_t otawa_kind_POPS__LB_SS_RB_(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if(0)
		__gtmp_0 = (2 | 8);
	else
		__gtmp_0 = 0;
	return ((((16 | 32) | 32768LU) | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_POPS__LB_SS_RB__0(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if(1)
		__gtmp_0 = (2 | 8);
	else
		__gtmp_0 = 0;
	return ((((16 | 32) | 32768LU) | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_ORRS_RD__RD(arm_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_RSBS_RD__RD___I0(arm_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_MVNS_RD__RD(arm_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_MULS_RD__RD(arm_inst_t *inst) {
	return ((512LU | 128) | 1024LU);

};

static otawa_kind_t otawa_kind_LSRS_RD__RD(arm_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_LSRS_RD__RD___ID(arm_inst_t *inst) {
	return ((512LU | 128) | 1073741824LU);

};

static otawa_kind_t otawa_kind_LSLS_RD__RD(arm_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_LSLS_RD__RD___ID(arm_inst_t *inst) {
	return ((512LU | 128) | 1073741824LU);

};

static otawa_kind_t otawa_kind_LDRSHS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_LDRSBS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_LDRHS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_LDRHS_RD___LT_RD___I0XX_RT_(arm_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_LDRBS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_LDRBS_RD___LT_RD___ID_RT_(arm_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_LDRS_RD___LT_SP___I0XX_RT_(arm_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_LDRS_RD___LT_PC___I0XX_RT_(arm_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_LDRS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_LDRS_RD___LT_RD___I0XX_RT_(arm_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_LDMIAS_RD___LB_S_RB_(arm_inst_t *inst) {
	return (((16 | 32) | 32768LU) | 128);

};

static otawa_kind_t otawa_kind_EORS_RD__RD(arm_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_CMPS_RD__S(arm_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_CMPS_RD__RD(arm_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_CMPS_RD___ID(arm_inst_t *inst) {
	return ((512LU | 128) | 1073741824LU);

};

static otawa_kind_t otawa_kind_CMNS_RD__RD(arm_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_CBZS_RD__D(arm_inst_t *inst) {
	return (2 | 1);

};

static otawa_kind_t otawa_kind_BXS_S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(ARM_BXS_S_i_x_rm_r)) == 14))
		__gtmp_0 = 8;
	else
		__gtmp_0 = 0;
	return ((2 | 16777216LU) | __gtmp_0);

};

static otawa_kind_t otawa_kind_BLXS_S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(ARM_BLXS_S_i_x_rm_r)) == 14))
		__gtmp_0 = 8;
	else
		__gtmp_0 = 0;
	return (((2 | 16777216LU) | 4) | __gtmp_0);

};

static otawa_kind_t otawa_kind_BKPT__ID(arm_inst_t *inst) {
	return (2 | 8192LU);

};

static otawa_kind_t otawa_kind_BICS_RD__RD(arm_inst_t *inst) {
	return ((512LU | 128) | 1073741824LU);

};

static otawa_kind_t otawa_kind_BS_N__40(arm_inst_t *inst) {
	return 2;

};

static otawa_kind_t otawa_kind_S_N_08X(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if(((((uint32_t)(ARM_S_N_08X_i_x_cond)) != 14) || (((uint32_t)(ARM_S_N_08X_i_x_cond)) != 15)))
		__gtmp_0 = 1;
	else
		__gtmp_0 = 0;
	if((((uint32_t)(ARM_S_N_08X_i_x_cond)) == 15))
		__gtmp_1 = 8192LU;
	else
		__gtmp_1 = 0;
	return ((2 | __gtmp_0) | __gtmp_1);

};

static otawa_kind_t otawa_kind_ASRS_RD__RD(arm_inst_t *inst) {
	return ((512LU | 128) | 1073741824LU);

};

static otawa_kind_t otawa_kind_ASRS_RD__RD___ID(arm_inst_t *inst) {
	return ((512LU | 128) | 1073741824LU);

};

static otawa_kind_t otawa_kind_ANDS_RD__RD(arm_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_ADDS_S__S(arm_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_ADDS_RD__RD__RD(arm_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_ADDS_SP__SP___ID(arm_inst_t *inst) {
	return ((512LU | 128) | 1073741824LU);

};

static otawa_kind_t otawa_kind_ADDS_RD__SP___ID(arm_inst_t *inst) {
	return ((512LU | 128) | 1073741824LU);

};

static otawa_kind_t otawa_kind_ADDS_RD__PC___ID(arm_inst_t *inst) {
	return ((512LU | 128) | 1073741824LU);

};

static otawa_kind_t otawa_kind_ADDS_RD___ID(arm_inst_t *inst) {
	return ((512LU | 128) | 1073741824LU);

};

static otawa_kind_t otawa_kind_ADDS_RD__RD___ID(arm_inst_t *inst) {
	return ((512LU | 128) | 1073741824LU);

};

static otawa_kind_t otawa_kind_ADCS_RD__RD(arm_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_MRCS_D__D__S__CRD__CRD__D(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDCSSS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if(((((uint32_t)(ARM_LDCSSS_D__D___LT_RD_RT___D_x_cond_cond)) == 14) || (((uint32_t)(ARM_LDCSSS_D__D___LT_RD_RT___D_x_cond_cond)) == 15)))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((16 | 128) | 32) | __gtmp_0);

};

static otawa_kind_t otawa_kind_LDCSSS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if(((((uint32_t)(ARM_LDCSSS_D__D___LT_RD_RT____ISD_x_cond_cond)) == 14) || (((uint32_t)(ARM_LDCSSS_D__D___LT_RD_RT____ISD_x_cond_cond)) == 15)))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((16 | 128) | 32) | __gtmp_0);

};

static otawa_kind_t otawa_kind_LDCSSS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if(((((uint32_t)(ARM_LDCSSS_D__D___LT_RD___ISD_RT__21_x_cond_cond)) == 14) || (((uint32_t)(ARM_LDCSSS_D__D___LT_RD___ISD_RT__21_x_cond_cond)) == 15)))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((16 | 128) | 32) | __gtmp_0);

};

static otawa_kind_t otawa_kind_LDCSSS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if(((((uint32_t)(ARM_LDCSSS_D__D___LT_RD___ISD_RT__x_cond_cond)) == 14) || (((uint32_t)(ARM_LDCSSS_D__D___LT_RD___ISD_RT__x_cond_cond)) == 15)))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((16 | 128) | 32) | __gtmp_0);

};

static otawa_kind_t otawa_kind_STCSSS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if(((((uint32_t)(ARM_STCSSS_D__D___LT_RD_RT___D_x_cond_cond)) == 14) || (((uint32_t)(ARM_STCSSS_D__D___LT_RD_RT___D_x_cond_cond)) == 15)))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((16 | 128) | 64) | __gtmp_0);

};

static otawa_kind_t otawa_kind_STCSSS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if(((((uint32_t)(ARM_STCSSS_D__D___LT_RD_RT____ISD_x_cond_cond)) == 14) || (((uint32_t)(ARM_STCSSS_D__D___LT_RD_RT____ISD_x_cond_cond)) == 15)))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((16 | 128) | 64) | __gtmp_0);

};

static otawa_kind_t otawa_kind_STCSSS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if(((((uint32_t)(ARM_STCSSS_D__D___LT_RD___ISD_RT__21_x_cond_cond)) == 14) || (((uint32_t)(ARM_STCSSS_D__D___LT_RD___ISD_RT__21_x_cond_cond)) == 15)))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((16 | 128) | 64) | __gtmp_0);

};

static otawa_kind_t otawa_kind_STCSSS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if(((((uint32_t)(ARM_STCSSS_D__D___LT_RD___ISD_RT__x_cond_cond)) == 14) || (((uint32_t)(ARM_STCSSS_D__D___LT_RD___ISD_RT__x_cond_cond)) == 15)))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((16 | 128) | 64) | __gtmp_0);

};

static otawa_kind_t otawa_kind_VSTRS_SD___LT_S___ISD_RT__0(arm_inst_t *inst) {
	return ((16 | 64) | 256LU);

};

static otawa_kind_t otawa_kind_VSTRS_DD___LT_S___ISD_RT__0(arm_inst_t *inst) {
	return ((16 | 64) | 256LU);

};

static otawa_kind_t otawa_kind_VSTMSSS_SS___LB_S_RB_(arm_inst_t *inst) {
	return (((16 | 64) | 256LU) | 32768LU);

};

static otawa_kind_t otawa_kind_VSTMSSS_SS___LB_S_RB__0(arm_inst_t *inst) {
	return (((16 | 64) | 256LU) | 32768LU);

};

static otawa_kind_t otawa_kind_VSTMSSS_SS___LB_S_RB__1(arm_inst_t *inst) {
	return (((16 | 64) | 256LU) | 32768LU);

};

static otawa_kind_t otawa_kind_VSTMSSS_SS___LB_S_RB__2(arm_inst_t *inst) {
	return (((16 | 64) | 256LU) | 32768LU);

};

static otawa_kind_t otawa_kind_VMULS_F64_DD__DD__DD_0(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VMULS_F32_SD__SD__SD_0(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VMUL_F32_QD__QD__QD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VMUL_F32_DD__DD__DD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VMOVS_DD__S__S_0(arm_inst_t *inst) {
	return ((512LU | 256LU) | 128);

};

static otawa_kind_t otawa_kind_VMOVS_SD__S_0(arm_inst_t *inst) {
	return ((512LU | 256LU) | 128);

};

static otawa_kind_t otawa_kind_VMOVS_F64_DD__DD_0(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VMOVS_F32_SD__SD_0(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VMOVS_F64_DD___ID_0(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VMOVS_F32_SD___ID_0(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VSS_F64_DD__DD__DD_0(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VSS_F32_SD__SD__SD_0(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VS_F32_QD__QD__QD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VS_F32_DD__DD__DD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VLDRS_DD___LT_S___ISD_RT__1(arm_inst_t *inst) {
	return ((16 | 32) | 256LU);

};

static otawa_kind_t otawa_kind_VLDRS_DD___LT_S___ISD_RT__2(arm_inst_t *inst) {
	return ((16 | 32) | 256LU);

};

static otawa_kind_t otawa_kind_VLDMDBS_S_21___LB_S_RB_(arm_inst_t *inst) {
	return (((16 | 32) | 256LU) | 32768LU);

};

static otawa_kind_t otawa_kind_VLDMIAS_SS___LB_S_RB_(arm_inst_t *inst) {
	return (((16 | 32) | 256LU) | 32768LU);

};

static otawa_kind_t otawa_kind_VLDMDBS_S_21___LB_S_RB__0(arm_inst_t *inst) {
	return (((16 | 32) | 256LU) | 32768LU);

};

static otawa_kind_t otawa_kind_VLDMIAS_SS___LB_S_RB__0(arm_inst_t *inst) {
	return (((16 | 32) | 256LU) | 32768LU);

};

static otawa_kind_t otawa_kind_VDIVS_F64_DD__DD__DD_0(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VDIVS_F32_SD__SD__SD_0(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VCVT_FD_FD_S__S(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VCVTSS_S_S_S_S(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VADDS_F64_DD__DD__DD_0(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VADDS_F32_SD__SD__SD_0(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VADD_F32_QD__QD__QD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_VADD_F32_DD__DD__DD(arm_inst_t *inst) {
	return (512LU | 256LU);

};

static otawa_kind_t otawa_kind_DMB_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MRSS_S__CPSR(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MRSS_S__CPSR_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_MRSS_S__CPSR_x_rn_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return (((512LU | 128) | __gtmp_0) | __gtmp_1);

};

static otawa_kind_t otawa_kind_MRSS_S__SPSR(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MRSS_S__SPSR_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_MRSS_S__SPSR_x_rn_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return (((512LU | 128) | __gtmp_0) | __gtmp_1);

};

static otawa_kind_t otawa_kind_MSRS_CPSR___S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR___S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_FSXC__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_FSXC__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_SXC__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_SXC__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_FXC__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_FXC__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_FSX__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_FSX__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_XC__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_XC__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_SC__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_SC__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_SX__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_SX__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_F__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_F__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_FX__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_FX__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_FS__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_FS__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_C__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_C__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_X__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_X__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_S__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_F__S_0(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_F__S_0_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR___S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR___S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_FSXC__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_FSXC__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_SXC__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_SXC__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_FXC__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_FXC__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_FSX__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_FSX__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_XC__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_XC__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_SC__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_SC__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_SX__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_SX__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_F__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_F__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_FX__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_FX__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_FS__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_FS__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_C__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_C__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_X__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_X__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_S__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_F__S_0(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_F__S_0_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR____ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR____ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_FSXC___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_FSXC___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_SXC___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_SXC___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_FXC___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_FXC___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_FSX___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_FSX___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_XC___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_XC___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_SC___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_SC___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_SX___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_SX___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_F___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_F___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_FX___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_FX___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_FS___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_FS___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_C___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_C___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_X___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_X___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_S___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_CPSR_F___ID_0(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_CPSR_F___ID_0_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR____ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR____ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_FSXC___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_FSXC___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_SXC___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_SXC___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_FXC___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_FXC___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_FSX___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_FSX___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_XC___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_XC___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_SC___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_SC___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_SX___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_SX___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_F___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_F___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_FX___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_FX___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_FS___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_FS___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_C___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_C___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_X___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_X___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_S___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_MSRS_SPSR_F___ID_0(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MSRS_SPSR_F___ID_0_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((512LU | 128) | __gtmp_0);

};

static otawa_kind_t otawa_kind_CDPSS_D__D__D__D__D__D(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_BFIS_S___ID___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CLZS_S__S_0(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_CLZS_S__S_0_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_CLZS_S__S_0_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return (((512LU | 128) | __gtmp_0) | __gtmp_1);

};

static otawa_kind_t otawa_kind_SWPS_S__S___LT_S_RT_(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_SWPS_S__S___LT_S_RT__x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_SWPS_S__S___LT_S_RT__x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | 8388608LU) | __gtmp_0) | __gtmp_1);

};

static otawa_kind_t otawa_kind_SWPSB_S__S___LT_S_RT_(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_SWPSB_S__S___LT_S_RT__x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_SWPSB_S__S___LT_S_RT__x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | 8388608LU) | __gtmp_0) | __gtmp_1);

};

static otawa_kind_t otawa_kind_UMLALSS_S__S__S__S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_UMLALSS_S__S__S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if(((((uint32_t)(ARM_UMLALSS_S__S__S__S_x_rdhi_r)) == 15) || (((uint32_t)(ARM_UMLALSS_S__S__S__S_x_rdlo_r)) == 15)))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return (((((512LU | 128) | 4194304LU) | 2097152LU) | __gtmp_0) | __gtmp_1);

};

static otawa_kind_t otawa_kind_SMLALSS_S__S__S__S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_SMLALSS_S__S__S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if(((((uint32_t)(ARM_SMLALSS_S__S__S__S_x_rdhi_r)) == 15) || (((uint32_t)(ARM_SMLALSS_S__S__S__S_x_rdlo_r)) == 15)))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return (((((512LU | 128) | 4194304LU) | 2097152LU) | __gtmp_0) | __gtmp_1);

};

static otawa_kind_t otawa_kind_UMULLSS_S__S__S__S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_UMULLSS_S__S__S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if(((((uint32_t)(ARM_UMULLSS_S__S__S__S_x_rdhi_r)) == 15) || (((uint32_t)(ARM_UMULLSS_S__S__S__S_x_rdlo_r)) == 15)))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return (((((512LU | 128) | 1024LU) | 2097152LU) | __gtmp_0) | __gtmp_1);

};

static otawa_kind_t otawa_kind_SMULLSS_S__S__S__S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_SMULLSS_S__S__S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if(((((uint32_t)(ARM_SMULLSS_S__S__S__S_x_rdhi_r)) == 15) || (((uint32_t)(ARM_SMULLSS_S__S__S__S_x_rdlo_r)) == 15)))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return (((((512LU | 128) | 1024LU) | 2097152LU) | __gtmp_0) | __gtmp_1);

};

static otawa_kind_t otawa_kind_MULSS_S__S__S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MULSS_S__S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_MULSS_S__S__S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | 1024LU) | __gtmp_0) | __gtmp_1);

};

static otawa_kind_t otawa_kind_MLASS_S__S__S__S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MLASS_S__S__S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_MLASS_S__S__S__S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | 4194304LU) | __gtmp_0) | __gtmp_1);

};

static otawa_kind_t otawa_kind_SWIS_D(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_SWIS_D_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((2 | 8192LU) | __gtmp_0);

};

static otawa_kind_t otawa_kind_LDMSS_SS___LB_S_RB_S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_LDMSS_SS___LB_S_RB_S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if(((((uint32_t)(ARM_LDMSS_SS___LB_S_RB_S_x_rn_r)) == 13) && (((uint32_t)(ARM_LDMSS_SS___LB_S_RB_S_x_reglist_r)) & (1 << 15))))
		__gtmp_1 = (2 | 8);
	else
		__gtmp_1 = 0;
	return ((((16 | 32768LU) | 32) | __gtmp_0) | __gtmp_1);

};

static otawa_kind_t otawa_kind_STMSS_SS___LB_S_RB_S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_STMSS_SS___LB_S_RB_S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((16 | 32768LU) | 64) | __gtmp_0);

};

static otawa_kind_t otawa_kind_STREXHS_S__S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STREXDS_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STREXBS_S__S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STREXS_S__S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDREXHS_S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDREXDS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDREXBS_S___LT_S_RT__1(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDREXS_S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRDS_S___LT_SS__S_IUSS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRSSH_S___LT_SS__SSSS(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_LDRSSH_S___LT_SS__SSSS_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_LDRSSH_S___LT_SS__SSSS_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((16 | 128) | __gtmp_0) | 32) | __gtmp_1);

};

static otawa_kind_t otawa_kind_LDRSSH_S___LT_SS__S_IUSS(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_LDRSSH_S___LT_SS__S_IUSS_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_LDRSSH_S___LT_SS__S_IUSS_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((16 | 128) | __gtmp_0) | 32) | __gtmp_1);

};

static otawa_kind_t otawa_kind_LDRSSB_S___LT_SS__SSSS(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_LDRSSB_S___LT_SS__SSSS_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_LDRSSB_S___LT_SS__SSSS_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((16 | 128) | __gtmp_0) | 32) | __gtmp_1);

};

static otawa_kind_t otawa_kind_LDRSSB_S___LT_SS__S_IUSS(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_LDRSSB_S___LT_SS__S_IUSS_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_LDRSSB_S___LT_SS__S_IUSS_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((16 | 128) | __gtmp_0) | 32) | __gtmp_1);

};

static otawa_kind_t otawa_kind_LDRSH_S___LT_SS__SSSS(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_LDRSH_S___LT_SS__SSSS_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_LDRSH_S___LT_SS__SSSS_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((16 | 128) | __gtmp_0) | 32) | __gtmp_1);

};

static otawa_kind_t otawa_kind_LDRSH_S___LT_SS__S_IUSS(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_LDRSH_S___LT_SS__S_IUSS_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_LDRSH_S___LT_SS__S_IUSS_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((16 | 128) | __gtmp_0) | 32) | __gtmp_1);

};

static otawa_kind_t otawa_kind_STRHS_S___LT_SS__SSSS(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_STRHS_S___LT_SS__SSSS_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((16 | 128) | __gtmp_0) | 64);

};

static otawa_kind_t otawa_kind_STRHS_S___LT_SS__S_IUSS(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_STRHS_S___LT_SS__S_IUSS_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((16 | 128) | __gtmp_0) | 64);

};

static otawa_kind_t otawa_kind_STRSSS_S___LT_SS__SS__S__IDSS(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_STRSSS_S___LT_SS__SS__S__IDSS_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((16 | 128) | 64) | __gtmp_0);

};

static otawa_kind_t otawa_kind_LDRSSS_S___LT_SS__SS__S__IDSS(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_LDRSSS_S___LT_SS__SS__S__IDSS_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_LDRSSS_S___LT_SS__SS__S__IDSS_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	if(((((uint32_t)(ARM_LDRSSS_S___LT_SS__SS__S__IDSS_x_rd_r)) == 15) && (((uint32_t)(ARM_LDRSSS_S___LT_SS__SS__S__IDSS_x_rn_r)) == 13)))
		__gtmp_2 = 8;
	else
		__gtmp_2 = 0;
	return (((((16 | 128) | 32) | __gtmp_0) | __gtmp_1) | __gtmp_2);

};

static otawa_kind_t otawa_kind_STRSSS_S___LT_SS__S_IDSS(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_STRSSS_S___LT_SS__S_IDSS_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((16 | 128) | 64) | __gtmp_0);

};

static otawa_kind_t otawa_kind_LDRSSS_S___LT_SS__S_IDSS(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_LDRSSS_S___LT_SS__S_IDSS_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_LDRSSS_S___LT_SS__S_IDSS_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	if(((((uint32_t)(ARM_LDRSSS_S___LT_SS__S_IDSS_x_rd_r)) == 15) && (((uint32_t)(ARM_LDRSSS_S___LT_SS__S_IDSS_x_rn_r)) == 13)))
		__gtmp_2 = 8;
	else
		__gtmp_2 = 0;
	return (((((16 | 128) | 32) | __gtmp_0) | __gtmp_1) | __gtmp_2);

};

static otawa_kind_t otawa_kind_BSS__40(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((ARM_BSS__40_x_cond_cond == 15))
		__gtmp_2 = 4;
	else {
		if(ARM_BSS__40_x_setl)
			__gtmp_0 = 4;
		else
			__gtmp_0 = 0;
		if((((uint32_t)(ARM_BSS__40_x_cond_cond)) == 14))
			__gtmp_1 = 0;
		else
			__gtmp_1 = 1;
		__gtmp_2 = (__gtmp_0 | __gtmp_1);
	}
	return (2 | __gtmp_2);

};

static otawa_kind_t otawa_kind_BLXS_S_0(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_BLXS_S_0_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((2 | 4) | __gtmp_0);

};

static otawa_kind_t otawa_kind_BXS_S_0(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(ARM_BXS_S_0_x_rd_r)) == 14))
		__gtmp_0 = 8;
	else
		__gtmp_0 = 0;
	if((((uint32_t)(((uint8_t)(ARM_BXS_S_0_x_cond_cond)))) == 14))
		__gtmp_1 = 0;
	else
		__gtmp_1 = 1;
	if((((uint32_t)(ARM_BXS_S_0_x_rd_r)) == 12))
		__gtmp_2 = 33554432LU;
	else
		__gtmp_2 = 0;
	return (((2 | __gtmp_0) | __gtmp_1) | __gtmp_2);

};

static otawa_kind_t otawa_kind_MOVS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MOVTS_S___ID_0(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_TSTS_S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_TSTS_S___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((((512LU | 128) | 268435456LU) | __gtmp_0) | 1073741824LU);

};

static otawa_kind_t otawa_kind_TSTS_S__S__S_S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_TSTS_S__S__S_S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((512LU | 128) | 268435456LU) | __gtmp_0);

};

static otawa_kind_t otawa_kind_TSTS_S__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_TSTS_S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((512LU | 128) | 268435456LU) | __gtmp_0);

};

static otawa_kind_t otawa_kind_TEQS_S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_TEQS_S___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((((512LU | 128) | 268435456LU) | __gtmp_0) | 1073741824LU);

};

static otawa_kind_t otawa_kind_TEQS_S__S__S_S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_TEQS_S__S__S_S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((512LU | 128) | 268435456LU) | __gtmp_0);

};

static otawa_kind_t otawa_kind_TEQS_S__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_TEQS_S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((512LU | 128) | 268435456LU) | __gtmp_0);

};

static otawa_kind_t otawa_kind_SUBSS_S__S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if(((((((uint32_t)(ARM_SUBSS_S__S___ID_x_rd_r)) == 15) && (((uint32_t)(ARM_SUBSS_S__S___ID_x_rn_r)) == 14)) && ARM_SUBSS_S__S___ID_x_sets_set) && (arm_rotate_right32(32, ((uint32_t)(ARM_SUBSS_S__S___ID_x_shifter_operand_v)), (((uint32_t)(ARM_SUBSS_S__S___ID_x_shifter_operand_rotate)) << 1)) == 4)))
		__gtmp_2 = ((2 | 8) | 8192LU);
	else {
		if((((uint32_t)(((uint8_t)(ARM_SUBSS_S__S___ID_x_cond_cond)))) == 14))
			__gtmp_0 = 0;
		else
			__gtmp_0 = 1;
		if((((uint32_t)(ARM_SUBSS_S__S___ID_x_rd_r)) == 15))
			__gtmp_1 = 2;
		else
			__gtmp_1 = 0;
		__gtmp_2 = ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 1073741824LU);
	}
	return __gtmp_2;

};

static otawa_kind_t otawa_kind_SUBSS_S__S__S__S_S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_SUBSS_S__S__S__S_S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_SUBSS_S__S__S__S_S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 536870912LU);

};

static otawa_kind_t otawa_kind_SUBSS_S__S__S(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_SUBSS_S__S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_SUBSS_S__S__S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	if(((((uint32_t)(ARM_SUBSS_S__S__S_x_shifter_operand_shiftAmt)) == 0) && (((uint32_t)(ARM_SUBSS_S__S__S_x_shifter_operand_shiftKind)) != 3)))
		__gtmp_2 = 0;
	else
		__gtmp_2 = (536870912LU | 1073741824LU);
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | __gtmp_2);

};

static otawa_kind_t otawa_kind_SBCSS_S__S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_SBCSS_S__S___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_SBCSS_S__S___ID_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 1073741824LU);

};

static otawa_kind_t otawa_kind_SBCSS_S__S__S__S_S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_SBCSS_S__S__S__S_S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_SBCSS_S__S__S__S_S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 536870912LU);

};

static otawa_kind_t otawa_kind_SBCSS_S__S__S(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_SBCSS_S__S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_SBCSS_S__S__S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	if(((((uint32_t)(ARM_SBCSS_S__S__S_x_shifter_operand_shiftAmt)) == 0) && (((uint32_t)(ARM_SBCSS_S__S__S_x_shifter_operand_shiftKind)) != 3)))
		__gtmp_2 = 0;
	else
		__gtmp_2 = (536870912LU | 1073741824LU);
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | __gtmp_2);

};

static otawa_kind_t otawa_kind_RSCSS_S__S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_RSCSS_S__S___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_RSCSS_S__S___ID_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 1073741824LU);

};

static otawa_kind_t otawa_kind_RSCSS_S__S__S__S_S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_RSCSS_S__S__S__S_S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_RSCSS_S__S__S__S_S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 536870912LU);

};

static otawa_kind_t otawa_kind_RSCSS_S__S__S(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_RSCSS_S__S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_RSCSS_S__S__S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	if(((((uint32_t)(ARM_RSCSS_S__S__S_x_shifter_operand_shiftAmt)) == 0) && (((uint32_t)(ARM_RSCSS_S__S__S_x_shifter_operand_shiftKind)) != 3)))
		__gtmp_2 = 0;
	else
		__gtmp_2 = (536870912LU | 1073741824LU);
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | __gtmp_2);

};

static otawa_kind_t otawa_kind_RSBSS_S__S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_RSBSS_S__S___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_RSBSS_S__S___ID_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 1073741824LU);

};

static otawa_kind_t otawa_kind_RSBSS_S__S__S__S_S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_RSBSS_S__S__S__S_S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_RSBSS_S__S__S__S_S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 536870912LU);

};

static otawa_kind_t otawa_kind_RSBSS_S__S__S(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_RSBSS_S__S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_RSBSS_S__S__S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	if(((((uint32_t)(ARM_RSBSS_S__S__S_x_shifter_operand_shiftAmt)) == 0) && (((uint32_t)(ARM_RSBSS_S__S__S_x_shifter_operand_shiftKind)) != 3)))
		__gtmp_2 = 0;
	else
		__gtmp_2 = (536870912LU | 1073741824LU);
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | __gtmp_2);

};

static otawa_kind_t otawa_kind_ORRSS_S__S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_ORRSS_S__S___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_ORRSS_S__S___ID_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 1073741824LU);

};

static otawa_kind_t otawa_kind_ORRSS_S__S__S__S_S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_ORRSS_S__S__S__S_S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_ORRSS_S__S__S__S_S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 536870912LU);

};

static otawa_kind_t otawa_kind_ORRSS_S__S__S(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_ORRSS_S__S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_ORRSS_S__S__S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	if(((((uint32_t)(ARM_ORRSS_S__S__S_x_shifter_operand_shiftAmt)) == 0) && (((uint32_t)(ARM_ORRSS_S__S__S_x_shifter_operand_shiftKind)) != 3)))
		__gtmp_2 = 0;
	else
		__gtmp_2 = (536870912LU | 1073741824LU);
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | __gtmp_2);

};

static otawa_kind_t otawa_kind_MVNSS_S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MVNSS_S___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_MVNSS_S___ID_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 1073741824LU);

};

static otawa_kind_t otawa_kind_MVNSS_S__S__S_S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MVNSS_S__S__S_S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_MVNSS_S__S__S_S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 536870912LU);

};

static otawa_kind_t otawa_kind_MVNSS_S__S(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MVNSS_S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_MVNSS_S__S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	if(((((uint32_t)(ARM_MVNSS_S__S_x_shifter_operand_shiftAmt)) == 0) && (((uint32_t)(ARM_MVNSS_S__S_x_shifter_operand_shiftKind)) != 3)))
		__gtmp_2 = 0;
	else
		__gtmp_2 = (536870912LU | 1073741824LU);
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | __gtmp_2);

};

static otawa_kind_t otawa_kind_MOVSS_S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_MOVSS_S___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_MOVSS_S___ID_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 1073741824LU);

};

static otawa_kind_t otawa_kind_MOVSS_S__S__S_S(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if(((((uint32_t)(((uint8_t)(ARM_MOVSS_S__S__S_S_x_cond_cond)))) != 15) && (((uint32_t)(ARM_MOVSS_S__S__S_S_x_rd_r)) == 15))) {
		if((((uint32_t)(ARM_MOVSS_S__S__S_S_x_shifter_operand_r_r)) == 14))
			__gtmp_0 = (8 | 2);
		else
			__gtmp_0 = 2;
		__gtmp_1 = __gtmp_0;
	}
	else
		__gtmp_1 = (512LU | 128);
	if((((uint32_t)(((uint8_t)(ARM_MOVSS_S__S__S_S_x_cond_cond)))) == 14))
		__gtmp_2 = 0;
	else
		__gtmp_2 = 1;
	return (__gtmp_1 | __gtmp_2);

};

static otawa_kind_t otawa_kind_MOVSS_S__S(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if(((((uint32_t)(((uint8_t)(ARM_MOVSS_S__S_x_cond_cond)))) != 15) && (((uint32_t)(ARM_MOVSS_S__S_x_rd_r)) == 15))) {
		if((((uint32_t)(ARM_MOVSS_S__S_x_shifter_operand_r_r)) == 14))
			__gtmp_0 = (8 | 2);
		else
			__gtmp_0 = 2;
		__gtmp_1 = __gtmp_0;
	}
	else
		__gtmp_1 = (512LU | 128);
	if((((uint32_t)(((uint8_t)(ARM_MOVSS_S__S_x_cond_cond)))) == 14))
		__gtmp_2 = 0;
	else
		__gtmp_2 = 1;
	return (__gtmp_1 | __gtmp_2);

};

static otawa_kind_t otawa_kind_EORSS_S__S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_EORSS_S__S___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_EORSS_S__S___ID_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 1073741824LU);

};

static otawa_kind_t otawa_kind_EORSS_S__S__S__S_S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_EORSS_S__S__S__S_S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_EORSS_S__S__S__S_S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 536870912LU);

};

static otawa_kind_t otawa_kind_EORSS_S__S__S(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_EORSS_S__S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_EORSS_S__S__S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	if(((((uint32_t)(ARM_EORSS_S__S__S_x_shifter_operand_shiftAmt)) == 0) && (((uint32_t)(ARM_EORSS_S__S__S_x_shifter_operand_shiftKind)) != 3)))
		__gtmp_2 = 0;
	else
		__gtmp_2 = (536870912LU | 1073741824LU);
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | __gtmp_2);

};

static otawa_kind_t otawa_kind_CMPS_S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_CMPS_S___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((((512LU | 128) | 268435456LU) | __gtmp_0) | 1073741824LU);

};

static otawa_kind_t otawa_kind_CMPS_S__S__S_S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_CMPS_S__S__S_S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((512LU | 128) | 268435456LU) | __gtmp_0);

};

static otawa_kind_t otawa_kind_CMPS_S__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_CMPS_S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((512LU | 128) | 268435456LU) | __gtmp_0);

};

static otawa_kind_t otawa_kind_CMNS_S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_CMNS_S___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return ((((512LU | 128) | 268435456LU) | __gtmp_0) | 1073741824LU);

};

static otawa_kind_t otawa_kind_CMNS_S__S__S_S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_CMNS_S__S__S_S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((512LU | 128) | 268435456LU) | __gtmp_0);

};

static otawa_kind_t otawa_kind_CMNS_S__S(arm_inst_t *inst) {
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_CMNS_S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (((512LU | 128) | 268435456LU) | __gtmp_0);

};

static otawa_kind_t otawa_kind_BICSS_S__S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_BICSS_S__S___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_BICSS_S__S___ID_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 1073741824LU);

};

static otawa_kind_t otawa_kind_BICSS_S__S__S__S_S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_BICSS_S__S__S__S_S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_BICSS_S__S__S__S_S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 536870912LU);

};

static otawa_kind_t otawa_kind_BICSS_S__S__S(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_BICSS_S__S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_BICSS_S__S__S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	if(((((uint32_t)(ARM_BICSS_S__S__S_x_shifter_operand_shiftAmt)) == 0) && (((uint32_t)(ARM_BICSS_S__S__S_x_shifter_operand_shiftKind)) != 3)))
		__gtmp_2 = 0;
	else
		__gtmp_2 = (536870912LU | 1073741824LU);
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | __gtmp_2);

};

static otawa_kind_t otawa_kind_ANDSS_S__S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_ANDSS_S__S___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_ANDSS_S__S___ID_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 1073741824LU);

};

static otawa_kind_t otawa_kind_ANDSS_S__S__S__S_S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_ANDSS_S__S__S__S_S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_ANDSS_S__S__S__S_S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 536870912LU);

};

static otawa_kind_t otawa_kind_ANDSS_S__S__S(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_ANDSS_S__S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_ANDSS_S__S__S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	if(((((uint32_t)(ARM_ANDSS_S__S__S_x_shifter_operand_shiftAmt)) == 0) && (((uint32_t)(ARM_ANDSS_S__S__S_x_shifter_operand_shiftKind)) != 3)))
		__gtmp_2 = 0;
	else
		__gtmp_2 = (536870912LU | 1073741824LU);
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | __gtmp_2);

};

static otawa_kind_t otawa_kind_ADDSS_S__S__S__S_S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_ADDSS_S__S__S__S_S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_ADDSS_S__S__S__S_S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 536870912LU);

};

static otawa_kind_t otawa_kind_ADDSS_S__S__S(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_ADDSS_S__S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_ADDSS_S__S__S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	if(((((uint32_t)(ARM_ADDSS_S__S__S_x_shifter_operand_shiftAmt)) == 0) && (((uint32_t)(ARM_ADDSS_S__S__S_x_shifter_operand_shiftKind)) != 3)))
		__gtmp_2 = 0;
	else
		__gtmp_2 = (536870912LU | 1073741824LU);
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | __gtmp_2);

};

static otawa_kind_t otawa_kind_ADCSS_S__S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_ADCSS_S__S___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_ADCSS_S__S___ID_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 1073741824LU);

};

static otawa_kind_t otawa_kind_ADCSS_S__S__S__S_S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_ADCSS_S__S__S__S_S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_ADCSS_S__S__S__S_S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 536870912LU);

};

static otawa_kind_t otawa_kind_ADCSS_S__S__S(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_ADCSS_S__S__S_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_ADCSS_S__S__S_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	if(((((uint32_t)(ARM_ADCSS_S__S__S_x_shifter_operand_shiftAmt)) == 0) && (((uint32_t)(ARM_ADCSS_S__S__S_x_shifter_operand_shiftKind)) != 3)))
		__gtmp_2 = 0;
	else
		__gtmp_2 = (536870912LU | 1073741824LU);
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | __gtmp_2);

};

static otawa_kind_t otawa_kind_ADDSS_S__S___ID(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(((uint8_t)(ARM_ADDSS_S__S___ID_x_cond_cond)))) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if((((uint32_t)(ARM_ADDSS_S__S___ID_x_rd_r)) == 15))
		__gtmp_1 = 2;
	else
		__gtmp_1 = 0;
	return ((((512LU | 128) | __gtmp_0) | __gtmp_1) | 1073741824LU);

};




/*** function table ***/
static fun_t kind_funs[] = {
	otawa_kind_UNKNOWN,
	otawa_kind_UXTAHS_S__S__SS,
	otawa_kind_UXTAB16S_S__S__SS,
	otawa_kind_UXTABS_S__S__SS,
	otawa_kind_USUB8S_S__S__S,
	otawa_kind_USUB16S_S__S__S,
	otawa_kind_USAXS_S__S__S,
	otawa_kind_USATS_S___ID__SS,
	otawa_kind_USADA8S_S__S__S__S,
	otawa_kind_UQSUB8S_S__S__S,
	otawa_kind_UQSUB16S_S__S__S,
	otawa_kind_UQSAXS_S__S__S,
	otawa_kind_UQASXS_S__S__S,
	otawa_kind_UQADD8S_S__S__S,
	otawa_kind_UQADD16S_S__S__S,
	otawa_kind_UMULLS_S__S__S__S,
	otawa_kind_UMLALS_S__S__S__S,
	otawa_kind_UMAALS_S__S__S__S,
	otawa_kind_UHSUB8S_S__S__S,
	otawa_kind_UHSUB16S_S__S__S,
	otawa_kind_UHSAXS_S__S__S,
	otawa_kind_UHASXS_S__S__S,
	otawa_kind_UHADD8S_S__S__S,
	otawa_kind_UHADD16S_S__S__S,
	otawa_kind_UDIVS_S__S__S,
	otawa_kind_UBFXS_S__S___ID___ID,
	otawa_kind_UASXS_S__S__S,
	otawa_kind_UADD8S_S__S__S,
	otawa_kind_UADD16S_S__S__S,
	otawa_kind_SXTAHS_S__S__SS,
	otawa_kind_SXTAB16S_S__S__SS,
	otawa_kind_SXTABS_S__S__SS,
	otawa_kind_SUBSS_W_S__S__SS,
	otawa_kind_SUBWS_S__S___ID_,
	otawa_kind_SUBSS_W_S__S___IU,
	otawa_kind_SSUB8S_S__S__S,
	otawa_kind_SSUB16S_S__S__S,
	otawa_kind_SSAXS_S__S__S,
	otawa_kind_SSATS_S___ID__SS,
	otawa_kind_SMULLS_S__S__S__S,
	otawa_kind_SMMLSSS_S__S__S__S,
	otawa_kind_SMMLASS_S__S__S__S,
	otawa_kind_SMLSLDSS_S__S__S__S,
	otawa_kind_SMLSDSS_S__S__S__S,
	otawa_kind_SMLAWSS_S__S__S__S,
	otawa_kind_SMLALDSS_S__S__S__S,
	otawa_kind_SMLALSSS_S__S__S__S,
	otawa_kind_SMLALS_S__S__S__S,
	otawa_kind_SMLADSS_S__S__S__S,
	otawa_kind_SMLASSS_S__S__S__S,
	otawa_kind_SHSUB8S_S__S__S,
	otawa_kind_SHSUB16S_S__S__S,
	otawa_kind_SHSAXS_S__S__S,
	otawa_kind_SHASXS_S__S__S,
	otawa_kind_SHADD8S_S__S__S,
	otawa_kind_SHADD16S_S__S__S,
	otawa_kind_SELS_S__S__S,
	otawa_kind_SDIVS_S__S__S,
	otawa_kind_SBFXS_S__S___ID___ID,
	otawa_kind_SBCSS_W_S__S__SS,
	otawa_kind_SBCSS_W_S__S___IU,
	otawa_kind_SASXS_S__S__S,
	otawa_kind_SADD8S_S__S__S,
	otawa_kind_SADD16S_S__S__S,
	otawa_kind_RSBSS_S__S__SS,
	otawa_kind_RORSS_W_S__S__S,
	otawa_kind_REVSHS_W_S__S,
	otawa_kind_REV16S_W_S__S,
	otawa_kind_REVS_W_S__S,
	otawa_kind_RBITS_S__S,
	otawa_kind_QSUB8S_S__S__S,
	otawa_kind_QSUB16S_S__S__S,
	otawa_kind_QSUBS_S__S__S,
	otawa_kind_QSAXS_S__S__S,
	otawa_kind_QDSUBS_S__S__S,
	otawa_kind_QDADDS_S__S__S,
	otawa_kind_QASXS_S__S__S,
	otawa_kind_QADD8S_S__S__S,
	otawa_kind_QADD16S_S__S__S,
	otawa_kind_QADDS_S__S__S,
	otawa_kind_PKHBTS_S__S__SS,
	otawa_kind_ORNSS_S__S__SS,
	otawa_kind_ORNSS_S__S___IU,
	otawa_kind_MRRCSS_D__D__S__S__CRD,
	otawa_kind_MRCSS_D__D__S__CRD__CRD___LB_D_RB_,
	otawa_kind_MLSS_S__S__S__S,
	otawa_kind_MLAS_S__S__S__S,
	otawa_kind_MCRRSS_D__D__S__S__CRD,
	otawa_kind_MCRSS_D__D__S__CRD__CRD___LB_D_RB_,
	otawa_kind_LSRSS_W_S__S__S,
	otawa_kind_LDMDBS_SS___LB_S_RB_,
	otawa_kind_EORSS_W_S__S__SS,
	otawa_kind_EORSS_W_S__S___IU,
	otawa_kind_CLZS_S__S,
	otawa_kind_CDPSS_D__D__CRD__CRD__CRD___LB_D_RB_,
	otawa_kind_BICSS_W_S__S__SS,
	otawa_kind_BICSS_W_S__S___IU,
	otawa_kind_BFIS_S__S___ID___ID,
	otawa_kind_BS_W_08X,
	otawa_kind_BS_W_08X_0,
	otawa_kind_MOVTS_S___ID,
	otawa_kind_ORRS_W_S__S__SS,
	otawa_kind_MOVWS_S___ID,
	otawa_kind_ORRSS_W_S__S___IU,
	otawa_kind_ASRSS_W_S__S__S,
	otawa_kind_ANDSS_W_S__S__SS,
	otawa_kind_ANDSS_W_S__S___IU,
	otawa_kind_ADDSS_W_S__S__SS,
	otawa_kind_ADDWS_S__S___ID_,
	otawa_kind_ADDSS_W_S__S___IU,
	otawa_kind_ADCSS_W_S__S__SS,
	otawa_kind_ADCSS_W_S__S___IU,
	otawa_kind_PLIS__LT_S__S_RT_,
	otawa_kind_PLIS__LT_PC_RT_,
	otawa_kind_PLIS__LT_S_RT_,
	otawa_kind_PLIS__LT_S_RT__0,
	otawa_kind_PLDSS__LT_S__S_RT_,
	otawa_kind_PLDSS__LT_S_RT_,
	otawa_kind_PLDSS__LT_S_RT__0,
	otawa_kind_RSBSS_W_S__S___ID,
	otawa_kind_LSLSS_W_S__S__S,
	otawa_kind_LDRDS_S__S___LT_SS,
	otawa_kind_STRDS_S__S___LT_SS,
	otawa_kind_STREXHS_S__S___LT_S_RT_,
	otawa_kind_STREXBS_S__S__S___LT_S_RT_,
	otawa_kind_STREXBS_S__S___LT_S_RT_,
	otawa_kind_STREXS_S__S___LT_S_RT_,
	otawa_kind_LDREXHS_S___LT_S_RT_,
	otawa_kind_LDREXBS_S___LT_S_RT_,
	otawa_kind_LDREXBS_S___LT_S_RT__0,
	otawa_kind_LDREXS_S___LT_S_RT_,
	otawa_kind_STMSS_SS___LB_SSSSSSSSSSSSSSS_RB_,
	otawa_kind_LDRSHS_S___LT_S_RT____IS0XX,
	otawa_kind_LDRSHS_S___LT_S___I0XX_RT_,
	otawa_kind_LDRSBS_S___LT_PC_RT_,
	otawa_kind_LDRSBS_S___LT_S_RT____IS0XX,
	otawa_kind_LDRSBS_S___LT_S___I0XX_RT_,
	otawa_kind_LDRBS_S___LT_S_RT____IS0XX,
	otawa_kind_LDRBS_W_S___LT_S___I0XX_RT_,
	otawa_kind_STRBS_S___LT_SS,
	otawa_kind_STRBS_W_S___LT_S___I0XX_RT_,
	otawa_kind_STRS_S___LT_S_RT____IS0XX,
	otawa_kind_STRS_W_S___LT_S___I0XX_RT_,
	otawa_kind_LDMSS_W_SS___LB_SSSSSSSSSSSSSSS_RB_,
	otawa_kind_STRHS_S___LT_S_RT____IS0XX,
	otawa_kind_STRHS_W_S___LT_S_RT_,
	otawa_kind_LDRHS_S___LT_S_RT____IS0XX,
	otawa_kind_LDRHS_W_S___LT_S_RT_,
	otawa_kind_LDRSHS_W_S___LT_S__S_RT_,
	otawa_kind_STRHS_W_S___LT_S__S_RT_,
	otawa_kind_LDRHS_W_S___LT_S__S_RT_,
	otawa_kind_LDRS_S___LT_S_RT____IS0XX,
	otawa_kind_LDRS_W_S___LT_S___I0XX_RT_,
	otawa_kind_LDRSHTS_S___LT_S_RT_,
	otawa_kind_LDRSBTS_S___LT_S_RT_,
	otawa_kind_STRTS_S___LT_S_RT_,
	otawa_kind_LDRTS_S___LT_S_RT_,
	otawa_kind_STRHTS_S___LT_S_RT_,
	otawa_kind_LDRHTS_S___LT_S_RT_,
	otawa_kind_STRBTS_S___LT_S_RT_,
	otawa_kind_LDRBTS_S___LT_S_RT_,
	otawa_kind_LDRSBS_W_S___LT_S__S_RT_,
	otawa_kind_STRBS_W_S___LT_S__S_RT_,
	otawa_kind_LDRBS_W_S___LT_S__S_RT_,
	otawa_kind_STRS_W_S___LT_S__S_RT_,
	otawa_kind_LDRS_W_S___LT_S__S_RT_,
	otawa_kind_LDC2SS_D__D___LT_RD_RT___D,
	otawa_kind_LDC2SS_D__D___LT_RD_RT____ISD,
	otawa_kind_LDC2SS_D__D___LT_RD___ISD_RT__21,
	otawa_kind_LDC2SS_D__D___LT_RD___ISD_RT_,
	otawa_kind_LDCSS_D__D___LT_RD_RT___D,
	otawa_kind_LDCSS_D__D___LT_RD_RT____ISD,
	otawa_kind_LDCSS_D__D___LT_RD___ISD_RT__21,
	otawa_kind_LDCSS_D__D___LT_RD___ISD_RT_,
	otawa_kind_STC2SS_D__D___LT_RD_RT___D,
	otawa_kind_STC2SS_D__D___LT_RD_RT____ISD,
	otawa_kind_STC2SS_D__D___LT_RD___ISD_RT__21,
	otawa_kind_STC2SS_D__D___LT_RD___ISD_RT_,
	otawa_kind_STCSS_D__D___LT_RD_RT___D,
	otawa_kind_STCSS_D__D___LT_RD_RT____ISD,
	otawa_kind_STCSS_D__D___LT_RD___ISD_RT__21,
	otawa_kind_STCSS_D__D___LT_RD___ISD_RT_,
	otawa_kind_BLXS_0X08X,
	otawa_kind_TBBS__LT_S__S_RT_,
	otawa_kind_BLS_0XX,
	otawa_kind_VSS_F64_DD__DD__DD,
	otawa_kind_VSS_F32_SD__SD__SD,
	otawa_kind_VSS_F32_QD__QD__QD,
	otawa_kind_VSS_F32_DD__DD__DD,
	otawa_kind_VPOPS__LB_SD_RB_,
	otawa_kind_VPOPS__LB_DD_RB_,
	otawa_kind_VADDS_F64_DD__DD__DD,
	otawa_kind_VADDS_F32_SD__SD__SD,
	otawa_kind_VADDS_F32_QD__QD__QD,
	otawa_kind_VADDS_F32_DD__DD__DD,
	otawa_kind_VCVTS_F64_S_DD__SD,
	otawa_kind_VCVTSS_U32_F64_SD__DD,
	otawa_kind_VCVTS_F32_S_SD__SD,
	otawa_kind_VPUSHS__LB_SD_RB_,
	otawa_kind_VPUSHS__LB_DD_RB_,
	otawa_kind_VMULS_F64_DD__DD__DD,
	otawa_kind_VMULS_F32_SD__SD__SD,
	otawa_kind_VMULS_F32_QD__QD__QD,
	otawa_kind_VMULS_F32_DD__DD__DD,
	otawa_kind_VMRSS_S__FPSCR,
	otawa_kind_VSTRS_SD___LT_S___ISD_RT_,
	otawa_kind_VSTRS_DD___LT_S___ISD_RT_,
	otawa_kind_VLDRS_DD___LT_S___ISD_RT_,
	otawa_kind_VLDRS_DD___LT_S___ISD_RT__0,
	otawa_kind_VDIVS_F64_DD__DD__DD,
	otawa_kind_VDIVS_F32_SD__SD__SD,
	otawa_kind_VSUBS_F64_DD__DD__DD,
	otawa_kind_VSUBS_F32_SD__SD__SD,
	otawa_kind_VMOVS_DD__S__S,
	otawa_kind_VMOVS_SD__S,
	otawa_kind_VMOVS_F64_DD__DD,
	otawa_kind_VMOVS_F32_SD__SD,
	otawa_kind_VMOVS_F64_DD___ID,
	otawa_kind_VMOVS_F32_SD___ID,
	otawa_kind_UXTHS_RD__RD,
	otawa_kind_UXTBS_RD__RD,
	otawa_kind_YIELDS,
	otawa_kind_MOVS_S__S,
	otawa_kind_MOVS_RD___ID,
	otawa_kind_TSTS_RD__RD,
	otawa_kind_SXTHS_RD__RD,
	otawa_kind_SXTBS_RD__RD,
	otawa_kind_SUBS_RD__RD__RD,
	otawa_kind_SUBS_SP___ID,
	otawa_kind_SUBS_RD___ID,
	otawa_kind_SUBS_RD__RD___ID,
	otawa_kind_STRHS_RD___LT_RD__RD__RT_,
	otawa_kind_STRHS_RD___LT_RD___I0XX_RT_,
	otawa_kind_STRBS_RD___LT_RD__RD_RT_,
	otawa_kind_STRBS_RD___LT_RD___ID_RT_,
	otawa_kind_STRS_RD___LT_SP___ID_RT_,
	otawa_kind_STRS_RD___LT_RD__RD_RT_,
	otawa_kind_STRS_RD___LT_RD___I0XX_RT_,
	otawa_kind_STMIAS_RD_21___LB_S_RB_,
	otawa_kind_SBCS_RD__RD,
	otawa_kind_RORS_RD__RD,
	otawa_kind_REVSHS_RD__RD,
	otawa_kind_REV16S_RD__RD,
	otawa_kind_REVS_RD__RD,
	otawa_kind_PUSHS__LB_SS_RB_,
	otawa_kind_PUSHS__LB_SS_RB__0,
	otawa_kind_POPS__LB_SS_RB_,
	otawa_kind_POPS__LB_SS_RB__0,
	otawa_kind_ORRS_RD__RD,
	otawa_kind_RSBS_RD__RD___I0,
	otawa_kind_MVNS_RD__RD,
	otawa_kind_MULS_RD__RD,
	otawa_kind_LSRS_RD__RD,
	otawa_kind_LSRS_RD__RD___ID,
	otawa_kind_LSLS_RD__RD,
	otawa_kind_LSLS_RD__RD___ID,
	otawa_kind_LDRSHS_RD___LT_RD__RD_RT_,
	otawa_kind_LDRSBS_RD___LT_RD__RD_RT_,
	otawa_kind_LDRHS_RD___LT_RD__RD_RT_,
	otawa_kind_LDRHS_RD___LT_RD___I0XX_RT_,
	otawa_kind_LDRBS_RD___LT_RD__RD_RT_,
	otawa_kind_LDRBS_RD___LT_RD___ID_RT_,
	otawa_kind_LDRS_RD___LT_SP___I0XX_RT_,
	otawa_kind_LDRS_RD___LT_PC___I0XX_RT_,
	otawa_kind_LDRS_RD___LT_RD__RD_RT_,
	otawa_kind_LDRS_RD___LT_RD___I0XX_RT_,
	otawa_kind_LDMIAS_RD___LB_S_RB_,
	otawa_kind_EORS_RD__RD,
	otawa_kind_CMPS_RD__S,
	otawa_kind_CMPS_RD__RD,
	otawa_kind_CMPS_RD___ID,
	otawa_kind_CMNS_RD__RD,
	otawa_kind_CBZS_RD__D,
	otawa_kind_BXS_S,
	otawa_kind_BLXS_S,
	otawa_kind_BKPT__ID,
	otawa_kind_BICS_RD__RD,
	otawa_kind_BS_N__40,
	otawa_kind_S_N_08X,
	otawa_kind_ASRS_RD__RD,
	otawa_kind_ASRS_RD__RD___ID,
	otawa_kind_ANDS_RD__RD,
	otawa_kind_ADDS_S__S,
	otawa_kind_ADDS_RD__RD__RD,
	otawa_kind_ADDS_SP__SP___ID,
	otawa_kind_ADDS_RD__SP___ID,
	otawa_kind_ADDS_RD__PC___ID,
	otawa_kind_ADDS_RD___ID,
	otawa_kind_ADDS_RD__RD___ID,
	otawa_kind_ADCS_RD__RD,
	otawa_kind_MRCS_D__D__S__CRD__CRD__D,
	otawa_kind_LDCSSS_D__D___LT_RD_RT___D,
	otawa_kind_LDCSSS_D__D___LT_RD_RT____ISD,
	otawa_kind_LDCSSS_D__D___LT_RD___ISD_RT__21,
	otawa_kind_LDCSSS_D__D___LT_RD___ISD_RT_,
	otawa_kind_STCSSS_D__D___LT_RD_RT___D,
	otawa_kind_STCSSS_D__D___LT_RD_RT____ISD,
	otawa_kind_STCSSS_D__D___LT_RD___ISD_RT__21,
	otawa_kind_STCSSS_D__D___LT_RD___ISD_RT_,
	otawa_kind_VSTRS_SD___LT_S___ISD_RT__0,
	otawa_kind_VSTRS_DD___LT_S___ISD_RT__0,
	otawa_kind_VSTMSSS_SS___LB_S_RB_,
	otawa_kind_VSTMSSS_SS___LB_S_RB__0,
	otawa_kind_VSTMSSS_SS___LB_S_RB__1,
	otawa_kind_VSTMSSS_SS___LB_S_RB__2,
	otawa_kind_VMULS_F64_DD__DD__DD_0,
	otawa_kind_VMULS_F32_SD__SD__SD_0,
	otawa_kind_VMUL_F32_QD__QD__QD,
	otawa_kind_VMUL_F32_DD__DD__DD,
	otawa_kind_VMOVS_DD__S__S_0,
	otawa_kind_VMOVS_SD__S_0,
	otawa_kind_VMOVS_F64_DD__DD_0,
	otawa_kind_VMOVS_F32_SD__SD_0,
	otawa_kind_VMOVS_F64_DD___ID_0,
	otawa_kind_VMOVS_F32_SD___ID_0,
	otawa_kind_VSS_F64_DD__DD__DD_0,
	otawa_kind_VSS_F32_SD__SD__SD_0,
	otawa_kind_VS_F32_QD__QD__QD,
	otawa_kind_VS_F32_DD__DD__DD,
	otawa_kind_VLDRS_DD___LT_S___ISD_RT__1,
	otawa_kind_VLDRS_DD___LT_S___ISD_RT__2,
	otawa_kind_VLDMDBS_S_21___LB_S_RB_,
	otawa_kind_VLDMIAS_SS___LB_S_RB_,
	otawa_kind_VLDMDBS_S_21___LB_S_RB__0,
	otawa_kind_VLDMIAS_SS___LB_S_RB__0,
	otawa_kind_VDIVS_F64_DD__DD__DD_0,
	otawa_kind_VDIVS_F32_SD__SD__SD_0,
	otawa_kind_VCVT_FD_FD_S__S,
	otawa_kind_VCVTSS_S_S_S_S,
	otawa_kind_VADDS_F64_DD__DD__DD_0,
	otawa_kind_VADDS_F32_SD__SD__SD_0,
	otawa_kind_VADD_F32_QD__QD__QD,
	otawa_kind_VADD_F32_DD__DD__DD,
	otawa_kind_DMB_S,
	otawa_kind_MRSS_S__CPSR,
	otawa_kind_MRSS_S__SPSR,
	otawa_kind_MSRS_CPSR___S,
	otawa_kind_MSRS_CPSR_FSXC__S,
	otawa_kind_MSRS_CPSR_SXC__S,
	otawa_kind_MSRS_CPSR_FXC__S,
	otawa_kind_MSRS_CPSR_FSX__S,
	otawa_kind_MSRS_CPSR_XC__S,
	otawa_kind_MSRS_CPSR_SC__S,
	otawa_kind_MSRS_CPSR_SX__S,
	otawa_kind_MSRS_CPSR_F__S,
	otawa_kind_MSRS_CPSR_FX__S,
	otawa_kind_MSRS_CPSR_FS__S,
	otawa_kind_MSRS_CPSR_C__S,
	otawa_kind_MSRS_CPSR_X__S,
	otawa_kind_MSRS_CPSR_S__S,
	otawa_kind_MSRS_CPSR_F__S_0,
	otawa_kind_MSRS_SPSR___S,
	otawa_kind_MSRS_SPSR_FSXC__S,
	otawa_kind_MSRS_SPSR_SXC__S,
	otawa_kind_MSRS_SPSR_FXC__S,
	otawa_kind_MSRS_SPSR_FSX__S,
	otawa_kind_MSRS_SPSR_XC__S,
	otawa_kind_MSRS_SPSR_SC__S,
	otawa_kind_MSRS_SPSR_SX__S,
	otawa_kind_MSRS_SPSR_F__S,
	otawa_kind_MSRS_SPSR_FX__S,
	otawa_kind_MSRS_SPSR_FS__S,
	otawa_kind_MSRS_SPSR_C__S,
	otawa_kind_MSRS_SPSR_X__S,
	otawa_kind_MSRS_SPSR_S__S,
	otawa_kind_MSRS_SPSR_F__S_0,
	otawa_kind_MSRS_CPSR____ID,
	otawa_kind_MSRS_CPSR_FSXC___ID,
	otawa_kind_MSRS_CPSR_SXC___ID,
	otawa_kind_MSRS_CPSR_FXC___ID,
	otawa_kind_MSRS_CPSR_FSX___ID,
	otawa_kind_MSRS_CPSR_XC___ID,
	otawa_kind_MSRS_CPSR_SC___ID,
	otawa_kind_MSRS_CPSR_SX___ID,
	otawa_kind_MSRS_CPSR_F___ID,
	otawa_kind_MSRS_CPSR_FX___ID,
	otawa_kind_MSRS_CPSR_FS___ID,
	otawa_kind_MSRS_CPSR_C___ID,
	otawa_kind_MSRS_CPSR_X___ID,
	otawa_kind_MSRS_CPSR_S___ID,
	otawa_kind_MSRS_CPSR_F___ID_0,
	otawa_kind_MSRS_SPSR____ID,
	otawa_kind_MSRS_SPSR_FSXC___ID,
	otawa_kind_MSRS_SPSR_SXC___ID,
	otawa_kind_MSRS_SPSR_FXC___ID,
	otawa_kind_MSRS_SPSR_FSX___ID,
	otawa_kind_MSRS_SPSR_XC___ID,
	otawa_kind_MSRS_SPSR_SC___ID,
	otawa_kind_MSRS_SPSR_SX___ID,
	otawa_kind_MSRS_SPSR_F___ID,
	otawa_kind_MSRS_SPSR_FX___ID,
	otawa_kind_MSRS_SPSR_FS___ID,
	otawa_kind_MSRS_SPSR_C___ID,
	otawa_kind_MSRS_SPSR_X___ID,
	otawa_kind_MSRS_SPSR_S___ID,
	otawa_kind_MSRS_SPSR_F___ID_0,
	otawa_kind_CDPSS_D__D__D__D__D__D,
	otawa_kind_BFIS_S___ID___ID,
	otawa_kind_CLZS_S__S_0,
	otawa_kind_SWPS_S__S___LT_S_RT_,
	otawa_kind_SWPSB_S__S___LT_S_RT_,
	otawa_kind_UMLALSS_S__S__S__S,
	otawa_kind_SMLALSS_S__S__S__S,
	otawa_kind_UMULLSS_S__S__S__S,
	otawa_kind_SMULLSS_S__S__S__S,
	otawa_kind_MULSS_S__S__S,
	otawa_kind_MLASS_S__S__S__S,
	otawa_kind_SWIS_D,
	otawa_kind_LDMSS_SS___LB_S_RB_S,
	otawa_kind_STMSS_SS___LB_S_RB_S,
	otawa_kind_STREXHS_S__S___LT_S_RT__0,
	otawa_kind_STREXDS_S__S___LT_S_RT_,
	otawa_kind_STREXBS_S__S___LT_S_RT__0,
	otawa_kind_STREXS_S__S___LT_S_RT__0,
	otawa_kind_LDREXHS_S___LT_S_RT__0,
	otawa_kind_LDREXDS_S___LT_S_RT_,
	otawa_kind_LDREXBS_S___LT_S_RT__1,
	otawa_kind_LDREXS_S___LT_S_RT__0,
	otawa_kind_STRDS_S___LT_SS__S_IUSS,
	otawa_kind_LDRSSH_S___LT_SS__SSSS,
	otawa_kind_LDRSSH_S___LT_SS__S_IUSS,
	otawa_kind_LDRSSB_S___LT_SS__SSSS,
	otawa_kind_LDRSSB_S___LT_SS__S_IUSS,
	otawa_kind_LDRSH_S___LT_SS__SSSS,
	otawa_kind_LDRSH_S___LT_SS__S_IUSS,
	otawa_kind_STRHS_S___LT_SS__SSSS,
	otawa_kind_STRHS_S___LT_SS__S_IUSS,
	otawa_kind_STRSSS_S___LT_SS__SS__S__IDSS,
	otawa_kind_LDRSSS_S___LT_SS__SS__S__IDSS,
	otawa_kind_STRSSS_S___LT_SS__S_IDSS,
	otawa_kind_LDRSSS_S___LT_SS__S_IDSS,
	otawa_kind_BSS__40,
	otawa_kind_BLXS_S_0,
	otawa_kind_BXS_S_0,
	otawa_kind_MOVS_S___ID,
	otawa_kind_MOVTS_S___ID_0,
	otawa_kind_TSTS_S___ID,
	otawa_kind_TSTS_S__S__S_S,
	otawa_kind_TSTS_S__S,
	otawa_kind_TEQS_S___ID,
	otawa_kind_TEQS_S__S__S_S,
	otawa_kind_TEQS_S__S,
	otawa_kind_SUBSS_S__S___ID,
	otawa_kind_SUBSS_S__S__S__S_S,
	otawa_kind_SUBSS_S__S__S,
	otawa_kind_SBCSS_S__S___ID,
	otawa_kind_SBCSS_S__S__S__S_S,
	otawa_kind_SBCSS_S__S__S,
	otawa_kind_RSCSS_S__S___ID,
	otawa_kind_RSCSS_S__S__S__S_S,
	otawa_kind_RSCSS_S__S__S,
	otawa_kind_RSBSS_S__S___ID,
	otawa_kind_RSBSS_S__S__S__S_S,
	otawa_kind_RSBSS_S__S__S,
	otawa_kind_ORRSS_S__S___ID,
	otawa_kind_ORRSS_S__S__S__S_S,
	otawa_kind_ORRSS_S__S__S,
	otawa_kind_MVNSS_S___ID,
	otawa_kind_MVNSS_S__S__S_S,
	otawa_kind_MVNSS_S__S,
	otawa_kind_MOVSS_S___ID,
	otawa_kind_MOVSS_S__S__S_S,
	otawa_kind_MOVSS_S__S,
	otawa_kind_EORSS_S__S___ID,
	otawa_kind_EORSS_S__S__S__S_S,
	otawa_kind_EORSS_S__S__S,
	otawa_kind_CMPS_S___ID,
	otawa_kind_CMPS_S__S__S_S,
	otawa_kind_CMPS_S__S,
	otawa_kind_CMNS_S___ID,
	otawa_kind_CMNS_S__S__S_S,
	otawa_kind_CMNS_S__S,
	otawa_kind_BICSS_S__S___ID,
	otawa_kind_BICSS_S__S__S__S_S,
	otawa_kind_BICSS_S__S__S,
	otawa_kind_ANDSS_S__S___ID,
	otawa_kind_ANDSS_S__S__S__S_S,
	otawa_kind_ANDSS_S__S__S,
	otawa_kind_ADDSS_S__S__S__S_S,
	otawa_kind_ADDSS_S__S__S,
	otawa_kind_ADCSS_S__S___ID,
	otawa_kind_ADCSS_S__S__S__S_S,
	otawa_kind_ADCSS_S__S__S,
	otawa_kind_ADDSS_S__S___ID
};

/**
 * Get the OTAWA kind of the instruction.
 * @return OTAWA kind.
 */
otawa_kind_t arm_kind(arm_inst_t *inst) {
	return kind_funs[inst->ident](inst);
}

#ifdef __cplusplus
}
#endif
