/* Generated by gliss-attr (118/04/09 13:06:16) copyright (c) 2009 IRIT - UPS */

#include <arm/api.h>
#include <arm/id.h>
#include <arm/macros.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef t::uint16 (*multi_fun_t)(arm_inst_t *inst);

static t::uint16 otawa_multi_UNKNOWN(arm_inst_t *inst) {
        return 0;
}

static t::uint16 otawa_multi_UXTAHS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UXTAB16S_S__S__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UXTABS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_USUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_USUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_USAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_USATS_S___ID__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_USADA8S_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UQSUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UQSUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UQSAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UQASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UQADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UQADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UMULLS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UMLALS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UMAALS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UHSUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UHSUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UHSAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UHASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UHADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UHADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UDIVS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UBFXS_S__S___ID___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SXTAHS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SXTAB16S_S__S__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SXTABS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SUBSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SUBWS_S__S___ID_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SUBSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SSUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SSUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SSAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SSATS_S___ID__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SMULLS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SMMLSSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SMMLASS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SMLSLDSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SMLSDSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SMLAWSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SMLALDSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SMLALSSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SMLALS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SMLADSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SMLASSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SHSUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SHSUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SHSAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SHASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SHADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SHADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SELS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SDIVS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SBFXS_S__S___ID___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SBCSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SBCSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RSBSS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RORSS_W_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_REVSHS_W_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_REV16S_W_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_REVS_W_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RBITS_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_QSUB8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_QSUB16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_QSUBS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_QSAXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_QDSUBS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_QDADDS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_QASXS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_QADD8S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_QADD16S_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_QADDS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_PKHBTS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ORNSS_S__S__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ORNSS_S__S___IU(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MRRCSS_D__D__S__S__CRD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MRCSS_D__D__S__CRD__CRD___LB_D_RB_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MLSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MLAS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MCRRSS_D__D__S__S__CRD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MCRSS_D__D__S__CRD__CRD___LB_D_RB_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LSRSS_W_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDMDBS_SS___LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_EORSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_EORSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CLZS_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CDPSS_D__D__CRD__CRD__CRD___LB_D_RB_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BICSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BICSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BFIS_S__S___ID___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BS_W_08X(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BS_W_08X_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MOVTS_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ORRS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MOVWS_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ORRSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ASRSS_W_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ANDSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ANDSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDWS_S__S___ID_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADCSS_W_S__S__SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADCSS_W_S__S___IU(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_PLIS__LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_PLIS__LT_PC_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_PLIS__LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_PLIS__LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_PLDSS__LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_PLDSS__LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_PLDSS__LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RSBSS_W_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LSLSS_W_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRDS_S__S___LT_SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRDS_S__S___LT_SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STREXHS_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STREXBS_S__S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STREXBS_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STREXS_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDREXHS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDREXBS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDREXBS_S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDREXS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STMSS_SS___LB_SSSSSSSSSSSSSSS_RB_(arm_inst_t *inst) {
	return ARM_STMSS_SS___LB_SSSSSSSSSSSSSSS_RB__i_x_register_list__l;

};

static t::uint16 otawa_multi_LDRSHS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSHS_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSBS_S___LT_PC_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSBS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSBS_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRBS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRBS_W_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRBS_S___LT_SS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRBS_W_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRS_W_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDMSS_W_SS___LB_SSSSSSSSSSSSSSS_RB_(arm_inst_t *inst) {
	return ARM_LDMSS_W_SS___LB_SSSSSSSSSSSSSSS_RB__i_x_register_list__l;

};

static t::uint16 otawa_multi_STRHS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRHS_W_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRHS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRHS_W_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSHS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRHS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRHS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRS_S___LT_S_RT____IS0XX(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRS_W_S___LT_S___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSHTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSBTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRHTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRHTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRBTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRBTS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSBS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRBS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRBS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRS_W_S___LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDC2SS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDC2SS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDC2SS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDC2SS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDCSS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDCSS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDCSS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDCSS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STC2SS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STC2SS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STC2SS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STC2SS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STCSS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STCSS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STCSS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STCSS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BLXS_0X08X(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_TBBS__LT_S__S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BLS_0XX(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VSS_F64_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VSS_F32_SD__SD__SD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VSS_F32_QD__QD__QD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VSS_F32_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VPOPS__LB_SD_RB_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VPOPS__LB_DD_RB_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VADDS_F64_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VADDS_F32_SD__SD__SD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VADDS_F32_QD__QD__QD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VADDS_F32_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VCVTS_F64_S_DD__SD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VCVTSS_U32_F64_SD__DD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VCVTS_F32_S_SD__SD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VPUSHS__LB_SD_RB_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VPUSHS__LB_DD_RB_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMULS_F64_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMULS_F32_SD__SD__SD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMULS_F32_QD__QD__QD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMULS_F32_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMRSS_S__FPSCR(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VSTRS_SD___LT_S___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VSTRS_DD___LT_S___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VLDRS_DD___LT_S___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VLDRS_DD___LT_S___ISD_RT__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VDIVS_F64_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VDIVS_F32_SD__SD__SD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VSUBS_F64_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VSUBS_F32_SD__SD__SD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMOVS_DD__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMOVS_SD__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMOVS_F64_DD__DD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMOVS_F32_SD__SD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMOVS_F64_DD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMOVS_F32_SD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UXTHS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UXTBS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_YIELDS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MOVS_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MOVS_RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_TSTS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SXTHS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SXTBS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SUBS_RD__RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SUBS_SP___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SUBS_RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SUBS_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRHS_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRHS_RD___LT_RD___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRBS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRBS_RD___LT_RD___ID_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRS_RD___LT_SP___ID_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRS_RD___LT_RD___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STMIAS_RD_21___LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SBCS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RORS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_REVSHS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_REV16S_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_REVS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_PUSHS__LB_SS_RB_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_PUSHS__LB_SS_RB__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_POPS__LB_SS_RB_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_POPS__LB_SS_RB__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ORRS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RSBS_RD__RD___I0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MVNS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MULS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LSRS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LSRS_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LSLS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LSLS_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSHS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSBS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRHS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRHS_RD___LT_RD___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRBS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRBS_RD___LT_RD___ID_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRS_RD___LT_SP___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRS_RD___LT_PC___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRS_RD___LT_RD__RD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRS_RD___LT_RD___I0XX_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDMIAS_RD___LB_S_RB_(arm_inst_t *inst) {
	return ARM_LDMIAS_RD___LB_S_RB__i_x_llist_r;

};

static t::uint16 otawa_multi_EORS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMPS_RD__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMPS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMPS_RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMNS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CBZS_RD__D(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BXS_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BLXS_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BKPT__ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BICS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BS_N__40(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_S_N_08X(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ASRS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ASRS_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ANDS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDS_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDS_RD__RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDS_SP__SP___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDS_RD__SP___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDS_RD__PC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDS_RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDS_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADCS_RD__RD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MRCS_D__D__S__CRD__CRD__D(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDCSSS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDCSSS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDCSSS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDCSSS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STCSSS_D__D___LT_RD_RT___D(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STCSSS_D__D___LT_RD_RT____ISD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STCSSS_D__D___LT_RD___ISD_RT__21(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STCSSS_D__D___LT_RD___ISD_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VSTRS_SD___LT_S___ISD_RT__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VSTRS_DD___LT_S___ISD_RT__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VSTMSSS_SS___LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VSTMSSS_SS___LB_S_RB__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VSTMSSS_SS___LB_S_RB__1(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VSTMSSS_SS___LB_S_RB__2(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMULS_F64_DD__DD__DD_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMULS_F32_SD__SD__SD_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMUL_F32_QD__QD__QD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMUL_F32_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMOVS_DD__S__S_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMOVS_SD__S_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMOVS_F64_DD__DD_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMOVS_F32_SD__SD_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMOVS_F64_DD___ID_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VMOVS_F32_SD___ID_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VSS_F64_DD__DD__DD_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VSS_F32_SD__SD__SD_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VS_F32_QD__QD__QD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VS_F32_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VLDRS_DD___LT_S___ISD_RT__1(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VLDRS_DD___LT_S___ISD_RT__2(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VLDMDBS_S_21___LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VLDMIAS_SS___LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VLDMDBS_S_21___LB_S_RB__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VLDMIAS_SS___LB_S_RB__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VDIVS_F64_DD__DD__DD_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VDIVS_F32_SD__SD__SD_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VCVT_FD_FD_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VCVTSS_S_S_S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VADDS_F64_DD__DD__DD_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VADDS_F32_SD__SD__SD_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VADD_F32_QD__QD__QD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_VADD_F32_DD__DD__DD(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_DMB_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MRSS_S__CPSR(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MRSS_S__SPSR(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR___S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FSXC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_SXC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FXC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FSX__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_XC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_SC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_SX__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_F__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FX__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FS__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_C__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_X__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_F__S_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR___S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FSXC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_SXC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FXC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FSX__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_XC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_SC__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_SX__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_F__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FX__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FS__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_C__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_X__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_F__S_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR____ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FSXC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_SXC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FXC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FSX___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_XC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_SC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_SX___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_F___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FX___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_FS___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_C___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_X___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_CPSR_F___ID_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR____ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FSXC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_SXC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FXC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FSX___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_XC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_SC___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_SX___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_F___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FX___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_FS___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_C___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_X___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MSRS_SPSR_F___ID_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CDPSS_D__D__D__D__D__D(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BFIS_S___ID___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CLZS_S__S_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SWPS_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SWPSB_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UMLALSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SMLALSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_UMULLSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SMULLSS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MULSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MLASS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SWIS_D(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDMSS_SS___LB_S_RB_S(arm_inst_t *inst) {
	return ARM_LDMSS_SS___LB_S_RB_S_x_reglist_r;

};

static t::uint16 otawa_multi_STMSS_SS___LB_S_RB_S(arm_inst_t *inst) {
	return ARM_STMSS_SS___LB_S_RB_S_x_reglist_r;

};

static t::uint16 otawa_multi_STREXHS_S__S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STREXDS_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STREXBS_S__S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STREXS_S__S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDREXHS_S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDREXDS_S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDREXBS_S___LT_S_RT__1(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDREXS_S___LT_S_RT__0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRDS_S___LT_SS__S_IUSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSSH_S___LT_SS__SSSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSSH_S___LT_SS__S_IUSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSSB_S___LT_SS__SSSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSSB_S___LT_SS__S_IUSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSH_S___LT_SS__SSSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSH_S___LT_SS__S_IUSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRHS_S___LT_SS__SSSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRHS_S___LT_SS__S_IUSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRSSS_S___LT_SS__SS__S__IDSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSSS_S___LT_SS__SS__S__IDSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_STRSSS_S___LT_SS__S_IDSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_LDRSSS_S___LT_SS__S_IDSS(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BSS__40(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BLXS_S_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BXS_S_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MOVS_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MOVTS_S___ID_0(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_TSTS_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_TSTS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_TSTS_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_TEQS_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_TEQS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_TEQS_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SUBSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SUBSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SUBSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SBCSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SBCSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_SBCSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RSCSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RSCSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RSCSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RSBSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RSBSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_RSBSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ORRSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ORRSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ORRSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MVNSS_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MVNSS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MVNSS_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MOVSS_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MOVSS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_MOVSS_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_EORSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_EORSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_EORSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMPS_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMPS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMPS_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMNS_S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMNS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_CMNS_S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BICSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BICSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_BICSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ANDSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ANDSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ANDSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADCSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADCSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADCSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static t::uint16 otawa_multi_ADDSS_S__S___ID(arm_inst_t *inst) {
return 0;
};




/* function table */
static multi_fun_t arm_multi_table[] = {
	otawa_multi_UNKNOWN,
	otawa_multi_UXTAHS_S__S__SS,
	otawa_multi_UXTAB16S_S__S__SS,
	otawa_multi_UXTABS_S__S__SS,
	otawa_multi_USUB8S_S__S__S,
	otawa_multi_USUB16S_S__S__S,
	otawa_multi_USAXS_S__S__S,
	otawa_multi_USATS_S___ID__SS,
	otawa_multi_USADA8S_S__S__S__S,
	otawa_multi_UQSUB8S_S__S__S,
	otawa_multi_UQSUB16S_S__S__S,
	otawa_multi_UQSAXS_S__S__S,
	otawa_multi_UQASXS_S__S__S,
	otawa_multi_UQADD8S_S__S__S,
	otawa_multi_UQADD16S_S__S__S,
	otawa_multi_UMULLS_S__S__S__S,
	otawa_multi_UMLALS_S__S__S__S,
	otawa_multi_UMAALS_S__S__S__S,
	otawa_multi_UHSUB8S_S__S__S,
	otawa_multi_UHSUB16S_S__S__S,
	otawa_multi_UHSAXS_S__S__S,
	otawa_multi_UHASXS_S__S__S,
	otawa_multi_UHADD8S_S__S__S,
	otawa_multi_UHADD16S_S__S__S,
	otawa_multi_UDIVS_S__S__S,
	otawa_multi_UBFXS_S__S___ID___ID,
	otawa_multi_UASXS_S__S__S,
	otawa_multi_UADD8S_S__S__S,
	otawa_multi_UADD16S_S__S__S,
	otawa_multi_SXTAHS_S__S__SS,
	otawa_multi_SXTAB16S_S__S__SS,
	otawa_multi_SXTABS_S__S__SS,
	otawa_multi_SUBSS_W_S__S__SS,
	otawa_multi_SUBWS_S__S___ID_,
	otawa_multi_SUBSS_W_S__S___IU,
	otawa_multi_SSUB8S_S__S__S,
	otawa_multi_SSUB16S_S__S__S,
	otawa_multi_SSAXS_S__S__S,
	otawa_multi_SSATS_S___ID__SS,
	otawa_multi_SMULLS_S__S__S__S,
	otawa_multi_SMMLSSS_S__S__S__S,
	otawa_multi_SMMLASS_S__S__S__S,
	otawa_multi_SMLSLDSS_S__S__S__S,
	otawa_multi_SMLSDSS_S__S__S__S,
	otawa_multi_SMLAWSS_S__S__S__S,
	otawa_multi_SMLALDSS_S__S__S__S,
	otawa_multi_SMLALSSS_S__S__S__S,
	otawa_multi_SMLALS_S__S__S__S,
	otawa_multi_SMLADSS_S__S__S__S,
	otawa_multi_SMLASSS_S__S__S__S,
	otawa_multi_SHSUB8S_S__S__S,
	otawa_multi_SHSUB16S_S__S__S,
	otawa_multi_SHSAXS_S__S__S,
	otawa_multi_SHASXS_S__S__S,
	otawa_multi_SHADD8S_S__S__S,
	otawa_multi_SHADD16S_S__S__S,
	otawa_multi_SELS_S__S__S,
	otawa_multi_SDIVS_S__S__S,
	otawa_multi_SBFXS_S__S___ID___ID,
	otawa_multi_SBCSS_W_S__S__SS,
	otawa_multi_SBCSS_W_S__S___IU,
	otawa_multi_SASXS_S__S__S,
	otawa_multi_SADD8S_S__S__S,
	otawa_multi_SADD16S_S__S__S,
	otawa_multi_RSBSS_S__S__SS,
	otawa_multi_RORSS_W_S__S__S,
	otawa_multi_REVSHS_W_S__S,
	otawa_multi_REV16S_W_S__S,
	otawa_multi_REVS_W_S__S,
	otawa_multi_RBITS_S__S,
	otawa_multi_QSUB8S_S__S__S,
	otawa_multi_QSUB16S_S__S__S,
	otawa_multi_QSUBS_S__S__S,
	otawa_multi_QSAXS_S__S__S,
	otawa_multi_QDSUBS_S__S__S,
	otawa_multi_QDADDS_S__S__S,
	otawa_multi_QASXS_S__S__S,
	otawa_multi_QADD8S_S__S__S,
	otawa_multi_QADD16S_S__S__S,
	otawa_multi_QADDS_S__S__S,
	otawa_multi_PKHBTS_S__S__SS,
	otawa_multi_ORNSS_S__S__SS,
	otawa_multi_ORNSS_S__S___IU,
	otawa_multi_MRRCSS_D__D__S__S__CRD,
	otawa_multi_MRCSS_D__D__S__CRD__CRD___LB_D_RB_,
	otawa_multi_MLSS_S__S__S__S,
	otawa_multi_MLAS_S__S__S__S,
	otawa_multi_MCRRSS_D__D__S__S__CRD,
	otawa_multi_MCRSS_D__D__S__CRD__CRD___LB_D_RB_,
	otawa_multi_LSRSS_W_S__S__S,
	otawa_multi_LDMDBS_SS___LB_S_RB_,
	otawa_multi_EORSS_W_S__S__SS,
	otawa_multi_EORSS_W_S__S___IU,
	otawa_multi_CLZS_S__S,
	otawa_multi_CDPSS_D__D__CRD__CRD__CRD___LB_D_RB_,
	otawa_multi_BICSS_W_S__S__SS,
	otawa_multi_BICSS_W_S__S___IU,
	otawa_multi_BFIS_S__S___ID___ID,
	otawa_multi_BS_W_08X,
	otawa_multi_BS_W_08X_0,
	otawa_multi_MOVTS_S___ID,
	otawa_multi_ORRS_W_S__S__SS,
	otawa_multi_MOVWS_S___ID,
	otawa_multi_ORRSS_W_S__S___IU,
	otawa_multi_ASRSS_W_S__S__S,
	otawa_multi_ANDSS_W_S__S__SS,
	otawa_multi_ANDSS_W_S__S___IU,
	otawa_multi_ADDSS_W_S__S__SS,
	otawa_multi_ADDWS_S__S___ID_,
	otawa_multi_ADDSS_W_S__S___IU,
	otawa_multi_ADCSS_W_S__S__SS,
	otawa_multi_ADCSS_W_S__S___IU,
	otawa_multi_PLIS__LT_S__S_RT_,
	otawa_multi_PLIS__LT_PC_RT_,
	otawa_multi_PLIS__LT_S_RT_,
	otawa_multi_PLIS__LT_S_RT__0,
	otawa_multi_PLDSS__LT_S__S_RT_,
	otawa_multi_PLDSS__LT_S_RT_,
	otawa_multi_PLDSS__LT_S_RT__0,
	otawa_multi_RSBSS_W_S__S___ID,
	otawa_multi_LSLSS_W_S__S__S,
	otawa_multi_LDRDS_S__S___LT_SS,
	otawa_multi_STRDS_S__S___LT_SS,
	otawa_multi_STREXHS_S__S___LT_S_RT_,
	otawa_multi_STREXBS_S__S__S___LT_S_RT_,
	otawa_multi_STREXBS_S__S___LT_S_RT_,
	otawa_multi_STREXS_S__S___LT_S_RT_,
	otawa_multi_LDREXHS_S___LT_S_RT_,
	otawa_multi_LDREXBS_S___LT_S_RT_,
	otawa_multi_LDREXBS_S___LT_S_RT__0,
	otawa_multi_LDREXS_S___LT_S_RT_,
	otawa_multi_STMSS_SS___LB_SSSSSSSSSSSSSSS_RB_,
	otawa_multi_LDRSHS_S___LT_S_RT____IS0XX,
	otawa_multi_LDRSHS_S___LT_S___I0XX_RT_,
	otawa_multi_LDRSBS_S___LT_PC_RT_,
	otawa_multi_LDRSBS_S___LT_S_RT____IS0XX,
	otawa_multi_LDRSBS_S___LT_S___I0XX_RT_,
	otawa_multi_LDRBS_S___LT_S_RT____IS0XX,
	otawa_multi_LDRBS_W_S___LT_S___I0XX_RT_,
	otawa_multi_STRBS_S___LT_SS,
	otawa_multi_STRBS_W_S___LT_S___I0XX_RT_,
	otawa_multi_STRS_S___LT_S_RT____IS0XX,
	otawa_multi_STRS_W_S___LT_S___I0XX_RT_,
	otawa_multi_LDMSS_W_SS___LB_SSSSSSSSSSSSSSS_RB_,
	otawa_multi_STRHS_S___LT_S_RT____IS0XX,
	otawa_multi_STRHS_W_S___LT_S_RT_,
	otawa_multi_LDRHS_S___LT_S_RT____IS0XX,
	otawa_multi_LDRHS_W_S___LT_S_RT_,
	otawa_multi_LDRSHS_W_S___LT_S__S_RT_,
	otawa_multi_STRHS_W_S___LT_S__S_RT_,
	otawa_multi_LDRHS_W_S___LT_S__S_RT_,
	otawa_multi_LDRS_S___LT_S_RT____IS0XX,
	otawa_multi_LDRS_W_S___LT_S___I0XX_RT_,
	otawa_multi_LDRSHTS_S___LT_S_RT_,
	otawa_multi_LDRSBTS_S___LT_S_RT_,
	otawa_multi_STRTS_S___LT_S_RT_,
	otawa_multi_LDRTS_S___LT_S_RT_,
	otawa_multi_STRHTS_S___LT_S_RT_,
	otawa_multi_LDRHTS_S___LT_S_RT_,
	otawa_multi_STRBTS_S___LT_S_RT_,
	otawa_multi_LDRBTS_S___LT_S_RT_,
	otawa_multi_LDRSBS_W_S___LT_S__S_RT_,
	otawa_multi_STRBS_W_S___LT_S__S_RT_,
	otawa_multi_LDRBS_W_S___LT_S__S_RT_,
	otawa_multi_STRS_W_S___LT_S__S_RT_,
	otawa_multi_LDRS_W_S___LT_S__S_RT_,
	otawa_multi_LDC2SS_D__D___LT_RD_RT___D,
	otawa_multi_LDC2SS_D__D___LT_RD_RT____ISD,
	otawa_multi_LDC2SS_D__D___LT_RD___ISD_RT__21,
	otawa_multi_LDC2SS_D__D___LT_RD___ISD_RT_,
	otawa_multi_LDCSS_D__D___LT_RD_RT___D,
	otawa_multi_LDCSS_D__D___LT_RD_RT____ISD,
	otawa_multi_LDCSS_D__D___LT_RD___ISD_RT__21,
	otawa_multi_LDCSS_D__D___LT_RD___ISD_RT_,
	otawa_multi_STC2SS_D__D___LT_RD_RT___D,
	otawa_multi_STC2SS_D__D___LT_RD_RT____ISD,
	otawa_multi_STC2SS_D__D___LT_RD___ISD_RT__21,
	otawa_multi_STC2SS_D__D___LT_RD___ISD_RT_,
	otawa_multi_STCSS_D__D___LT_RD_RT___D,
	otawa_multi_STCSS_D__D___LT_RD_RT____ISD,
	otawa_multi_STCSS_D__D___LT_RD___ISD_RT__21,
	otawa_multi_STCSS_D__D___LT_RD___ISD_RT_,
	otawa_multi_BLXS_0X08X,
	otawa_multi_TBBS__LT_S__S_RT_,
	otawa_multi_BLS_0XX,
	otawa_multi_VSS_F64_DD__DD__DD,
	otawa_multi_VSS_F32_SD__SD__SD,
	otawa_multi_VSS_F32_QD__QD__QD,
	otawa_multi_VSS_F32_DD__DD__DD,
	otawa_multi_VPOPS__LB_SD_RB_,
	otawa_multi_VPOPS__LB_DD_RB_,
	otawa_multi_VADDS_F64_DD__DD__DD,
	otawa_multi_VADDS_F32_SD__SD__SD,
	otawa_multi_VADDS_F32_QD__QD__QD,
	otawa_multi_VADDS_F32_DD__DD__DD,
	otawa_multi_VCVTS_F64_S_DD__SD,
	otawa_multi_VCVTSS_U32_F64_SD__DD,
	otawa_multi_VCVTS_F32_S_SD__SD,
	otawa_multi_VPUSHS__LB_SD_RB_,
	otawa_multi_VPUSHS__LB_DD_RB_,
	otawa_multi_VMULS_F64_DD__DD__DD,
	otawa_multi_VMULS_F32_SD__SD__SD,
	otawa_multi_VMULS_F32_QD__QD__QD,
	otawa_multi_VMULS_F32_DD__DD__DD,
	otawa_multi_VMRSS_S__FPSCR,
	otawa_multi_VSTRS_SD___LT_S___ISD_RT_,
	otawa_multi_VSTRS_DD___LT_S___ISD_RT_,
	otawa_multi_VLDRS_DD___LT_S___ISD_RT_,
	otawa_multi_VLDRS_DD___LT_S___ISD_RT__0,
	otawa_multi_VDIVS_F64_DD__DD__DD,
	otawa_multi_VDIVS_F32_SD__SD__SD,
	otawa_multi_VSUBS_F64_DD__DD__DD,
	otawa_multi_VSUBS_F32_SD__SD__SD,
	otawa_multi_VMOVS_DD__S__S,
	otawa_multi_VMOVS_SD__S,
	otawa_multi_VMOVS_F64_DD__DD,
	otawa_multi_VMOVS_F32_SD__SD,
	otawa_multi_VMOVS_F64_DD___ID,
	otawa_multi_VMOVS_F32_SD___ID,
	otawa_multi_UXTHS_RD__RD,
	otawa_multi_UXTBS_RD__RD,
	otawa_multi_YIELDS,
	otawa_multi_MOVS_S__S,
	otawa_multi_MOVS_RD___ID,
	otawa_multi_TSTS_RD__RD,
	otawa_multi_SXTHS_RD__RD,
	otawa_multi_SXTBS_RD__RD,
	otawa_multi_SUBS_RD__RD__RD,
	otawa_multi_SUBS_SP___ID,
	otawa_multi_SUBS_RD___ID,
	otawa_multi_SUBS_RD__RD___ID,
	otawa_multi_STRHS_RD___LT_RD__RD__RT_,
	otawa_multi_STRHS_RD___LT_RD___I0XX_RT_,
	otawa_multi_STRBS_RD___LT_RD__RD_RT_,
	otawa_multi_STRBS_RD___LT_RD___ID_RT_,
	otawa_multi_STRS_RD___LT_SP___ID_RT_,
	otawa_multi_STRS_RD___LT_RD__RD_RT_,
	otawa_multi_STRS_RD___LT_RD___I0XX_RT_,
	otawa_multi_STMIAS_RD_21___LB_S_RB_,
	otawa_multi_SBCS_RD__RD,
	otawa_multi_RORS_RD__RD,
	otawa_multi_REVSHS_RD__RD,
	otawa_multi_REV16S_RD__RD,
	otawa_multi_REVS_RD__RD,
	otawa_multi_PUSHS__LB_SS_RB_,
	otawa_multi_PUSHS__LB_SS_RB__0,
	otawa_multi_POPS__LB_SS_RB_,
	otawa_multi_POPS__LB_SS_RB__0,
	otawa_multi_ORRS_RD__RD,
	otawa_multi_RSBS_RD__RD___I0,
	otawa_multi_MVNS_RD__RD,
	otawa_multi_MULS_RD__RD,
	otawa_multi_LSRS_RD__RD,
	otawa_multi_LSRS_RD__RD___ID,
	otawa_multi_LSLS_RD__RD,
	otawa_multi_LSLS_RD__RD___ID,
	otawa_multi_LDRSHS_RD___LT_RD__RD_RT_,
	otawa_multi_LDRSBS_RD___LT_RD__RD_RT_,
	otawa_multi_LDRHS_RD___LT_RD__RD_RT_,
	otawa_multi_LDRHS_RD___LT_RD___I0XX_RT_,
	otawa_multi_LDRBS_RD___LT_RD__RD_RT_,
	otawa_multi_LDRBS_RD___LT_RD___ID_RT_,
	otawa_multi_LDRS_RD___LT_SP___I0XX_RT_,
	otawa_multi_LDRS_RD___LT_PC___I0XX_RT_,
	otawa_multi_LDRS_RD___LT_RD__RD_RT_,
	otawa_multi_LDRS_RD___LT_RD___I0XX_RT_,
	otawa_multi_LDMIAS_RD___LB_S_RB_,
	otawa_multi_EORS_RD__RD,
	otawa_multi_CMPS_RD__S,
	otawa_multi_CMPS_RD__RD,
	otawa_multi_CMPS_RD___ID,
	otawa_multi_CMNS_RD__RD,
	otawa_multi_CBZS_RD__D,
	otawa_multi_BXS_S,
	otawa_multi_BLXS_S,
	otawa_multi_BKPT__ID,
	otawa_multi_BICS_RD__RD,
	otawa_multi_BS_N__40,
	otawa_multi_S_N_08X,
	otawa_multi_ASRS_RD__RD,
	otawa_multi_ASRS_RD__RD___ID,
	otawa_multi_ANDS_RD__RD,
	otawa_multi_ADDS_S__S,
	otawa_multi_ADDS_RD__RD__RD,
	otawa_multi_ADDS_SP__SP___ID,
	otawa_multi_ADDS_RD__SP___ID,
	otawa_multi_ADDS_RD__PC___ID,
	otawa_multi_ADDS_RD___ID,
	otawa_multi_ADDS_RD__RD___ID,
	otawa_multi_ADCS_RD__RD,
	otawa_multi_MRCS_D__D__S__CRD__CRD__D,
	otawa_multi_LDCSSS_D__D___LT_RD_RT___D,
	otawa_multi_LDCSSS_D__D___LT_RD_RT____ISD,
	otawa_multi_LDCSSS_D__D___LT_RD___ISD_RT__21,
	otawa_multi_LDCSSS_D__D___LT_RD___ISD_RT_,
	otawa_multi_STCSSS_D__D___LT_RD_RT___D,
	otawa_multi_STCSSS_D__D___LT_RD_RT____ISD,
	otawa_multi_STCSSS_D__D___LT_RD___ISD_RT__21,
	otawa_multi_STCSSS_D__D___LT_RD___ISD_RT_,
	otawa_multi_VSTRS_SD___LT_S___ISD_RT__0,
	otawa_multi_VSTRS_DD___LT_S___ISD_RT__0,
	otawa_multi_VSTMSSS_SS___LB_S_RB_,
	otawa_multi_VSTMSSS_SS___LB_S_RB__0,
	otawa_multi_VSTMSSS_SS___LB_S_RB__1,
	otawa_multi_VSTMSSS_SS___LB_S_RB__2,
	otawa_multi_VMULS_F64_DD__DD__DD_0,
	otawa_multi_VMULS_F32_SD__SD__SD_0,
	otawa_multi_VMUL_F32_QD__QD__QD,
	otawa_multi_VMUL_F32_DD__DD__DD,
	otawa_multi_VMOVS_DD__S__S_0,
	otawa_multi_VMOVS_SD__S_0,
	otawa_multi_VMOVS_F64_DD__DD_0,
	otawa_multi_VMOVS_F32_SD__SD_0,
	otawa_multi_VMOVS_F64_DD___ID_0,
	otawa_multi_VMOVS_F32_SD___ID_0,
	otawa_multi_VSS_F64_DD__DD__DD_0,
	otawa_multi_VSS_F32_SD__SD__SD_0,
	otawa_multi_VS_F32_QD__QD__QD,
	otawa_multi_VS_F32_DD__DD__DD,
	otawa_multi_VLDRS_DD___LT_S___ISD_RT__1,
	otawa_multi_VLDRS_DD___LT_S___ISD_RT__2,
	otawa_multi_VLDMDBS_S_21___LB_S_RB_,
	otawa_multi_VLDMIAS_SS___LB_S_RB_,
	otawa_multi_VLDMDBS_S_21___LB_S_RB__0,
	otawa_multi_VLDMIAS_SS___LB_S_RB__0,
	otawa_multi_VDIVS_F64_DD__DD__DD_0,
	otawa_multi_VDIVS_F32_SD__SD__SD_0,
	otawa_multi_VCVT_FD_FD_S__S,
	otawa_multi_VCVTSS_S_S_S_S,
	otawa_multi_VADDS_F64_DD__DD__DD_0,
	otawa_multi_VADDS_F32_SD__SD__SD_0,
	otawa_multi_VADD_F32_QD__QD__QD,
	otawa_multi_VADD_F32_DD__DD__DD,
	otawa_multi_DMB_S,
	otawa_multi_MRSS_S__CPSR,
	otawa_multi_MRSS_S__SPSR,
	otawa_multi_MSRS_CPSR___S,
	otawa_multi_MSRS_CPSR_FSXC__S,
	otawa_multi_MSRS_CPSR_SXC__S,
	otawa_multi_MSRS_CPSR_FXC__S,
	otawa_multi_MSRS_CPSR_FSX__S,
	otawa_multi_MSRS_CPSR_XC__S,
	otawa_multi_MSRS_CPSR_SC__S,
	otawa_multi_MSRS_CPSR_SX__S,
	otawa_multi_MSRS_CPSR_F__S,
	otawa_multi_MSRS_CPSR_FX__S,
	otawa_multi_MSRS_CPSR_FS__S,
	otawa_multi_MSRS_CPSR_C__S,
	otawa_multi_MSRS_CPSR_X__S,
	otawa_multi_MSRS_CPSR_S__S,
	otawa_multi_MSRS_CPSR_F__S_0,
	otawa_multi_MSRS_SPSR___S,
	otawa_multi_MSRS_SPSR_FSXC__S,
	otawa_multi_MSRS_SPSR_SXC__S,
	otawa_multi_MSRS_SPSR_FXC__S,
	otawa_multi_MSRS_SPSR_FSX__S,
	otawa_multi_MSRS_SPSR_XC__S,
	otawa_multi_MSRS_SPSR_SC__S,
	otawa_multi_MSRS_SPSR_SX__S,
	otawa_multi_MSRS_SPSR_F__S,
	otawa_multi_MSRS_SPSR_FX__S,
	otawa_multi_MSRS_SPSR_FS__S,
	otawa_multi_MSRS_SPSR_C__S,
	otawa_multi_MSRS_SPSR_X__S,
	otawa_multi_MSRS_SPSR_S__S,
	otawa_multi_MSRS_SPSR_F__S_0,
	otawa_multi_MSRS_CPSR____ID,
	otawa_multi_MSRS_CPSR_FSXC___ID,
	otawa_multi_MSRS_CPSR_SXC___ID,
	otawa_multi_MSRS_CPSR_FXC___ID,
	otawa_multi_MSRS_CPSR_FSX___ID,
	otawa_multi_MSRS_CPSR_XC___ID,
	otawa_multi_MSRS_CPSR_SC___ID,
	otawa_multi_MSRS_CPSR_SX___ID,
	otawa_multi_MSRS_CPSR_F___ID,
	otawa_multi_MSRS_CPSR_FX___ID,
	otawa_multi_MSRS_CPSR_FS___ID,
	otawa_multi_MSRS_CPSR_C___ID,
	otawa_multi_MSRS_CPSR_X___ID,
	otawa_multi_MSRS_CPSR_S___ID,
	otawa_multi_MSRS_CPSR_F___ID_0,
	otawa_multi_MSRS_SPSR____ID,
	otawa_multi_MSRS_SPSR_FSXC___ID,
	otawa_multi_MSRS_SPSR_SXC___ID,
	otawa_multi_MSRS_SPSR_FXC___ID,
	otawa_multi_MSRS_SPSR_FSX___ID,
	otawa_multi_MSRS_SPSR_XC___ID,
	otawa_multi_MSRS_SPSR_SC___ID,
	otawa_multi_MSRS_SPSR_SX___ID,
	otawa_multi_MSRS_SPSR_F___ID,
	otawa_multi_MSRS_SPSR_FX___ID,
	otawa_multi_MSRS_SPSR_FS___ID,
	otawa_multi_MSRS_SPSR_C___ID,
	otawa_multi_MSRS_SPSR_X___ID,
	otawa_multi_MSRS_SPSR_S___ID,
	otawa_multi_MSRS_SPSR_F___ID_0,
	otawa_multi_CDPSS_D__D__D__D__D__D,
	otawa_multi_BFIS_S___ID___ID,
	otawa_multi_CLZS_S__S_0,
	otawa_multi_SWPS_S__S___LT_S_RT_,
	otawa_multi_SWPSB_S__S___LT_S_RT_,
	otawa_multi_UMLALSS_S__S__S__S,
	otawa_multi_SMLALSS_S__S__S__S,
	otawa_multi_UMULLSS_S__S__S__S,
	otawa_multi_SMULLSS_S__S__S__S,
	otawa_multi_MULSS_S__S__S,
	otawa_multi_MLASS_S__S__S__S,
	otawa_multi_SWIS_D,
	otawa_multi_LDMSS_SS___LB_S_RB_S,
	otawa_multi_STMSS_SS___LB_S_RB_S,
	otawa_multi_STREXHS_S__S___LT_S_RT__0,
	otawa_multi_STREXDS_S__S___LT_S_RT_,
	otawa_multi_STREXBS_S__S___LT_S_RT__0,
	otawa_multi_STREXS_S__S___LT_S_RT__0,
	otawa_multi_LDREXHS_S___LT_S_RT__0,
	otawa_multi_LDREXDS_S___LT_S_RT_,
	otawa_multi_LDREXBS_S___LT_S_RT__1,
	otawa_multi_LDREXS_S___LT_S_RT__0,
	otawa_multi_STRDS_S___LT_SS__S_IUSS,
	otawa_multi_LDRSSH_S___LT_SS__SSSS,
	otawa_multi_LDRSSH_S___LT_SS__S_IUSS,
	otawa_multi_LDRSSB_S___LT_SS__SSSS,
	otawa_multi_LDRSSB_S___LT_SS__S_IUSS,
	otawa_multi_LDRSH_S___LT_SS__SSSS,
	otawa_multi_LDRSH_S___LT_SS__S_IUSS,
	otawa_multi_STRHS_S___LT_SS__SSSS,
	otawa_multi_STRHS_S___LT_SS__S_IUSS,
	otawa_multi_STRSSS_S___LT_SS__SS__S__IDSS,
	otawa_multi_LDRSSS_S___LT_SS__SS__S__IDSS,
	otawa_multi_STRSSS_S___LT_SS__S_IDSS,
	otawa_multi_LDRSSS_S___LT_SS__S_IDSS,
	otawa_multi_BSS__40,
	otawa_multi_BLXS_S_0,
	otawa_multi_BXS_S_0,
	otawa_multi_MOVS_S___ID,
	otawa_multi_MOVTS_S___ID_0,
	otawa_multi_TSTS_S___ID,
	otawa_multi_TSTS_S__S__S_S,
	otawa_multi_TSTS_S__S,
	otawa_multi_TEQS_S___ID,
	otawa_multi_TEQS_S__S__S_S,
	otawa_multi_TEQS_S__S,
	otawa_multi_SUBSS_S__S___ID,
	otawa_multi_SUBSS_S__S__S__S_S,
	otawa_multi_SUBSS_S__S__S,
	otawa_multi_SBCSS_S__S___ID,
	otawa_multi_SBCSS_S__S__S__S_S,
	otawa_multi_SBCSS_S__S__S,
	otawa_multi_RSCSS_S__S___ID,
	otawa_multi_RSCSS_S__S__S__S_S,
	otawa_multi_RSCSS_S__S__S,
	otawa_multi_RSBSS_S__S___ID,
	otawa_multi_RSBSS_S__S__S__S_S,
	otawa_multi_RSBSS_S__S__S,
	otawa_multi_ORRSS_S__S___ID,
	otawa_multi_ORRSS_S__S__S__S_S,
	otawa_multi_ORRSS_S__S__S,
	otawa_multi_MVNSS_S___ID,
	otawa_multi_MVNSS_S__S__S_S,
	otawa_multi_MVNSS_S__S,
	otawa_multi_MOVSS_S___ID,
	otawa_multi_MOVSS_S__S__S_S,
	otawa_multi_MOVSS_S__S,
	otawa_multi_EORSS_S__S___ID,
	otawa_multi_EORSS_S__S__S__S_S,
	otawa_multi_EORSS_S__S__S,
	otawa_multi_CMPS_S___ID,
	otawa_multi_CMPS_S__S__S_S,
	otawa_multi_CMPS_S__S,
	otawa_multi_CMNS_S___ID,
	otawa_multi_CMNS_S__S__S_S,
	otawa_multi_CMNS_S__S,
	otawa_multi_BICSS_S__S___ID,
	otawa_multi_BICSS_S__S__S__S_S,
	otawa_multi_BICSS_S__S__S,
	otawa_multi_ANDSS_S__S___ID,
	otawa_multi_ANDSS_S__S__S__S_S,
	otawa_multi_ANDSS_S__S__S,
	otawa_multi_ADDSS_S__S__S__S_S,
	otawa_multi_ADDSS_S__S__S,
	otawa_multi_ADCSS_S__S___ID,
	otawa_multi_ADCSS_S__S__S__S_S,
	otawa_multi_ADCSS_S__S__S,
	otawa_multi_ADDSS_S__S___ID
};



/**
 * Get the multiple-register count of the instruction.
 * @return multiple-register count.
 */
t::uint16 arm_multi(arm_inst_t *inst) {
	return arm_multi_table[inst->ident](inst);
}

#ifdef __cplusplus
}
#endif

