/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#include <stdlib.h>
#include <stdio.h>
#include <arm/fetch.h>
#include <arm/decode.h> /* api.h will be in it, for fetch functions, decode_table.h also */
#include <arm/config.h> /* for memory endiannesses */
#include <arm/code.h>

#include "code_table.h"


/**
 * Execute the given instruction in the given state.
 * @param state		Current execution state.
 * @param inst		Current instruction to execute.
 */
void arm_execute(arm_state_t *state, arm_inst_t *inst)
{
	arm_code_table[inst->ident](state, inst);
}


/* End of file arm_code.c */
